from typing import Tuple, NamedTuple, List, Set, Dict
import numpy as np
from deepred.polaris_env.pokemon_red.enums import FixedPokemonType, Pokemon, GrowthRate, Move
from deepred.polaris_env.pokemon_red.pokemon_stats import PokemonsBaseStats

experience_caps = {
    GrowthRate.FAST: 800_000,
    GrowthRate.MEDIUM_FAST: 1_000_000,
    GrowthRate.MEDIUM_SLOW: 1_059_860,
    GrowthRate.SLOW: 1_250_000,
}

class PokemonData:

    
    def __init__(
            self,
            pokemon: Pokemon,
            types: Tuple[FixedPokemonType, FixedPokemonType],
            catch_rate: int,
            base_exp: int,
            exp_growth: GrowthRate,
            move_set: Set[Move],

    ):
        self.pokemon = pokemon
        self.base_stats = PokemonsBaseStats[pokemon]
        self.types = types
        self.catch_rate = catch_rate
        self.base_exp = base_exp
        self.exp_growth = exp_growth
        self.move_set = move_set

    def get_level(self, exp: int) -> int:
        """
        Gets the level for the given exp
        """
        if self.exp_growth == GrowthRate.MEDIUM_FAST:
            return int(exp**(1/3))
        elif self.exp_growth == GrowthRate.FAST:
            return int((exp * 5 / 4) ** (1 / 3))
        elif self.exp_growth == GrowthRate.MEDIUM_SLOW:
            roots = np.roots([6/5, -15, +100, -140-exp])
            for root in roots:
                if root.imag == 0:
                    return int(root.real)

        elif self.exp_growth == GrowthRate.SLOW:
            return int((exp * 4 / 5) ** (1 / 3))
        else:
            print("???")


    def get_exp(self, level: int) -> int:
        """
        Gets the exp required for the given level
        """
        if self.exp_growth == GrowthRate.MEDIUM_FAST:
            return int(level**3)
        elif self.exp_growth == GrowthRate.FAST:
            return int(4 * level ** 3 / 5)
        elif self.exp_growth == GrowthRate.MEDIUM_SLOW:
            return 6 * level ** 3 / 5 - 15 * level ** 2 + 100 * level - 140
        elif self.exp_growth == GrowthRate.SLOW:
            return int(5 * level ** 3 / 4)
        else:
            print("???")


PokemonDatas: Dict[Pokemon, PokemonData] = {
    Pokemon.PARASECT: PokemonData(pokemon=Pokemon.PARASECT, types=(FixedPokemonType.BUG, FixedPokemonType.GRASS), catch_rate=75, base_exp=128, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.LEECH_LIFE, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWORDS_DANCE, Move.STUN_SPORE, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.VENUSAUR: PokemonData(pokemon=Pokemon.VENUSAUR, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=45, base_exp=208, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.LEECH_SEED, Move.DOUBLE_EDGE, Move.CUT, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.GROWL, Move.VINE_WHIP, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.GLOOM: PokemonData(pokemon=Pokemon.GLOOM, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=120, base_exp=132, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.ABSORB, Move.REFLECT, Move.TAKE_DOWN, Move.REST, Move.POISONPOWDER, Move.SWORDS_DANCE, Move.STUN_SPORE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.GYARADOS: PokemonData(pokemon=Pokemon.GYARADOS, types=(FixedPokemonType.WATER, FixedPokemonType.FLYING), catch_rate=45, base_exp=214, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.BITE, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.ICE_BEAM, Move.THUNDER, Move.HYDRO_PUMP, Move.LEER, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.OMANYTE: PokemonData(pokemon=Pokemon.OMANYTE, types=(FixedPokemonType.ROCK, FixedPokemonType.WATER), catch_rate=45, base_exp=120, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.WITHDRAW, Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.POLIWRATH: PokemonData(pokemon=Pokemon.POLIWRATH, types=(FixedPokemonType.WATER, FixedPokemonType.FIGHTING), catch_rate=45, base_exp=185, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.HYPNOSIS, Move.HYPER_BEAM, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.DOUBLESLAP, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.ICE_BEAM, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.VILEPLUME: PokemonData(pokemon=Pokemon.VILEPLUME, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=45, base_exp=184, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.SLEEP_POWDER, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.STUN_SPORE, Move.PETAL_DANCE, Move.SUBSTITUTE, Move.ACID, Move.BIDE}),
    Pokemon.GRAVELER: PokemonData(pokemon=Pokemon.GRAVELER, types=(FixedPokemonType.ROCK, FixedPokemonType.GROUND), catch_rate=120, base_exp=134, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.EXPLOSION, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.DEFENSE_CURL}),
    Pokemon.PIKACHU: PokemonData(pokemon=Pokemon.PIKACHU, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=190, base_exp=82, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.TOXIC, Move.GROWL, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.SUBSTITUTE, Move.PAY_DAY, Move.REST, Move.SWIFT, Move.THUNDERSHOCK, Move.SKULL_BASH, Move.BIDE, Move.FLASH}),
    Pokemon.GENGAR: PokemonData(pokemon=Pokemon.GENGAR, types=(FixedPokemonType.GHOST, FixedPokemonType.POISON), catch_rate=45, base_exp=190, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MEGA_DRAIN, Move.NIGHT_SHADE, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.DREAM_EATER, Move.RAGE, Move.METRONOME, Move.THUNDERBOLT, Move.SUBMISSION, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.SELFDESTRUCT, Move.THUNDER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.CONFUSE_RAY, Move.REST, Move.LICK, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.HYPNO: PokemonData(pokemon=Pokemon.HYPNO, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=75, base_exp=165, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.CONFUSION, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.POUND, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.DREAM_EATER, Move.RAGE, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.PSYWAVE, Move.HYPNOSIS, Move.COUNTER, Move.HYPER_BEAM, Move.MEGA_KICK, Move.TOXIC, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DISABLE, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.RATTATA: PokemonData(pokemon=Pokemon.RATTATA, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=255, base_exp=57, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.THUNDER, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.KABUTO: PokemonData(pokemon=Pokemon.KABUTO, types=(FixedPokemonType.ROCK, FixedPokemonType.WATER), catch_rate=45, base_exp=119, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.REFLECT, Move.WATER_GUN, Move.SCRATCH, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.HARDEN, Move.BIDE}),
    Pokemon.SANDSLASH: PokemonData(pokemon=Pokemon.SANDSLASH, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=90, base_exp=163, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SAND_ATTACK, Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.CUT, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.EARTHQUAKE, Move.TOXIC, Move.HYPER_BEAM, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.SWORDS_DANCE, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.DITTO: PokemonData(pokemon=Pokemon.DITTO, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=35, base_exp=61, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.TRANSFORM, Move.NO_MOVE}),
    Pokemon.DROWZEE: PokemonData(pokemon=Pokemon.DROWZEE, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=190, base_exp=102, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.POUND, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.DREAM_EATER, Move.RAGE, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.PSYWAVE, Move.HYPNOSIS, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.SPEAROW: PokemonData(pokemon=Pokemon.SPEAROW, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=255, base_exp=58, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.PECK, Move.GROWL, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.KOFFING: PokemonData(pokemon=Pokemon.KOFFING, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=190, base_exp=114, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.THUNDER, Move.MIMIC, Move.EXPLOSION, Move.REST, Move.TACKLE, Move.SMOG, Move.THUNDERBOLT, Move.RAGE, Move.SUBSTITUTE, Move.DOUBLE_TEAM, Move.BIDE, Move.TOXIC}),
    Pokemon.DIGLETT: PokemonData(pokemon=Pokemon.DIGLETT, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=255, base_exp=81, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.ROCK_SLIDE, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.EARTHQUAKE, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.NINETALES: PokemonData(pokemon=Pokemon.NINETALES, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=75, base_exp=178, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.ROAR}),
    Pokemon.TENTACRUEL: PokemonData(pokemon=Pokemon.TENTACRUEL, types=(FixedPokemonType.WATER, FixedPokemonType.POISON), catch_rate=60, base_exp=205, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SKULL_BASH, Move.SUPERSONIC, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BLIZZARD, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.WRAP, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.ACID, Move.BIDE}),
    Pokemon.VAPOREON: PokemonData(pokemon=Pokemon.VAPOREON, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=45, base_exp=196, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SAND_ATTACK, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.AERODACTYL: PokemonData(pokemon=Pokemon.AERODACTYL, types=(FixedPokemonType.ROCK, FixedPokemonType.FLYING), catch_rate=45, base_exp=202, exp_growth=GrowthRate.SLOW, move_set={Move.FLY, Move.MIMIC, Move.WING_ATTACK, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.AGILITY, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.MAGIKARP: PokemonData(pokemon=Pokemon.MAGIKARP, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=255, base_exp=20, exp_growth=GrowthRate.SLOW, move_set={Move.SPLASH, Move.NO_MOVE}),
    Pokemon.MAGMAR: PokemonData(pokemon=Pokemon.MAGMAR, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=45, base_exp=167, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.FIRE_BLAST, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT}),
    Pokemon.GRIMER: PokemonData(pokemon=Pokemon.GRIMER, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=190, base_exp=90, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.POUND, Move.MEGA_DRAIN, Move.MIMIC, Move.EXPLOSION, Move.THUNDERBOLT, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.THUNDER, Move.DISABLE, Move.REST, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.SEEL: PokemonData(pokemon=Pokemon.SEEL, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=190, base_exp=100, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.HEADBUTT, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.PIDGEOT: PokemonData(pokemon=Pokemon.PIDGEOT, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=45, base_exp=172, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SAND_ATTACK, Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK, Move.GUST}),
    Pokemon.NIDORINO: PokemonData(pokemon=Pokemon.NIDORINO, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=120, base_exp=118, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.ICE_BEAM, Move.THUNDER, Move.LEER, Move.TAKE_DOWN, Move.REST, Move.HORN_ATTACK, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.JIGGLYPUFF: PokemonData(pokemon=Pokemon.JIGGLYPUFF, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=170, base_exp=76, exp_growth=GrowthRate.FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.SING, Move.REST, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.VENOMOTH: PokemonData(pokemon=Pokemon.VENOMOTH, types=(FixedPokemonType.BUG, FixedPokemonType.POISON), catch_rate=75, base_exp=138, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.PSYCHIC_M, Move.LEECH_LIFE, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.TACKLE, Move.RAGE, Move.PSYWAVE, Move.DOUBLE_TEAM, Move.REFLECT, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.DISABLE, Move.RAZOR_WIND, Move.REST, Move.POISONPOWDER, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.NIDORANM: PokemonData(pokemon=Pokemon.NIDORANM, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=235, base_exp=60, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.THUNDER, Move.LEER, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.EXEGGCUTE: PokemonData(pokemon=Pokemon.EXEGGCUTE, types=(FixedPokemonType.GRASS, FixedPokemonType.PSYCHIC_TYPE), catch_rate=90, base_exp=98, exp_growth=GrowthRate.SLOW, move_set={Move.PSYCHIC_M, Move.EGG_BOMB, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.RAGE, Move.PSYWAVE, Move.DOUBLE_TEAM, Move.REFLECT, Move.HYPNOSIS, Move.SELFDESTRUCT, Move.TAKE_DOWN, Move.REST, Move.BARRAGE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.RAPIDASH: PokemonData(pokemon=Pokemon.RAPIDASH, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=60, base_exp=192, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.EMBER, Move.MIMIC, Move.STOMP, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.GROWL, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.PERSIAN: PokemonData(pokemon=Pokemon.PERSIAN, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=90, base_exp=148, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.BITE, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.GROWL, Move.SCREECH, Move.HYPER_BEAM, Move.SCRATCH, Move.THUNDER, Move.TAKE_DOWN, Move.PAY_DAY, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.SLOWPOKE: PokemonData(pokemon=Pokemon.SLOWPOKE, types=(FixedPokemonType.WATER, FixedPokemonType.PSYCHIC_TYPE), catch_rate=190, base_exp=99, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.CONFUSION, Move.PSYCHIC_M, Move.BLIZZARD, Move.REFLECT, Move.BUBBLEBEAM, Move.THUNDER_WAVE, Move.REST, Move.FISSURE, Move.SWIFT, Move.SKULL_BASH, Move.TELEPORT, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.FLAREON: PokemonData(pokemon=Pokemon.FLAREON, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=45, base_exp=198, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SAND_ATTACK, Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.POLIWHIRL: PokemonData(pokemon=Pokemon.POLIWHIRL, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=120, base_exp=131, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BUBBLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.BUBBLEBEAM, Move.COUNTER, Move.WATER_GUN, Move.HYPNOSIS, Move.EARTHQUAKE, Move.TOXIC, Move.MEGA_KICK, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.JOLTEON: PokemonData(pokemon=Pokemon.JOLTEON, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=45, base_exp=197, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SAND_ATTACK, Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.TOXIC, Move.REFLECT, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.THUNDER, Move.SUBSTITUTE, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.THUNDERSHOCK, Move.SKULL_BASH, Move.BIDE, Move.FLASH}),
    Pokemon.WIGGLYTUFF: PokemonData(pokemon=Pokemon.WIGGLYTUFF, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=50, base_exp=109, exp_growth=GrowthRate.FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.SING, Move.DOUBLESLAP, Move.DISABLE, Move.REST, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.DEFENSE_CURL, Move.FLASH}),
    Pokemon.BULBASAUR: PokemonData(pokemon=Pokemon.BULBASAUR, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=45, base_exp=64, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.GROWL, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.KABUTOPS: PokemonData(pokemon=Pokemon.KABUTOPS, types=(FixedPokemonType.ROCK, FixedPokemonType.WATER), catch_rate=45, base_exp=201, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SKULL_BASH, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.ABSORB, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.SCRATCH, Move.ICE_BEAM, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.HARDEN, Move.BIDE}),
    Pokemon.MUK: PokemonData(pokemon=Pokemon.MUK, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=75, base_exp=157, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.POUND, Move.MEGA_DRAIN, Move.MIMIC, Move.EXPLOSION, Move.POISON_GAS, Move.RAGE, Move.BODY_SLAM, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.HYPER_BEAM, Move.SELFDESTRUCT, Move.FIRE_BLAST, Move.THUNDER, Move.DISABLE, Move.REST, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.DODUO: PokemonData(pokemon=Pokemon.DODUO, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=190, base_exp=96, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.PECK, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.GASTLY: PokemonData(pokemon=Pokemon.GASTLY, types=(FixedPokemonType.GHOST, FixedPokemonType.POISON), catch_rate=190, base_exp=95, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.PSYCHIC_M, Move.MEGA_DRAIN, Move.NIGHT_SHADE, Move.MIMIC, Move.EXPLOSION, Move.THUNDERBOLT, Move.PSYWAVE, Move.DREAM_EATER, Move.RAGE, Move.DOUBLE_TEAM, Move.SELFDESTRUCT, Move.THUNDER, Move.CONFUSE_RAY, Move.REST, Move.LICK, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.IVYSAUR: PokemonData(pokemon=Pokemon.IVYSAUR, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=45, base_exp=141, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.LEECH_SEED, Move.DOUBLE_EDGE, Move.CUT, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.GROWL, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.GOLEM: PokemonData(pokemon=Pokemon.GOLEM, types=(FixedPokemonType.ROCK, FixedPokemonType.GROUND), catch_rate=45, base_exp=177, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.EXPLOSION, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.DEFENSE_CURL}),
    Pokemon.WARTORTLE: PokemonData(pokemon=Pokemon.WARTORTLE, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=45, base_exp=143, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.BUBBLE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.COUNTER, Move.WATER_GUN, Move.TOXIC, Move.MEGA_KICK, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.SLOWBRO: PokemonData(pokemon=Pokemon.SLOWBRO, types=(FixedPokemonType.WATER, FixedPokemonType.PSYCHIC_TYPE), catch_rate=75, base_exp=164, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.CONFUSION, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.DISABLE, Move.REST, Move.FISSURE, Move.SWIFT, Move.SKULL_BASH, Move.TELEPORT, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.HEADBUTT, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.PIDGEY: PokemonData(pokemon=Pokemon.PIDGEY, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=255, base_exp=55, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK, Move.GUST}),
    Pokemon.BEEDRILL: PokemonData(pokemon=Pokemon.BEEDRILL, types=(FixedPokemonType.BUG, FixedPokemonType.POISON), catch_rate=45, base_exp=159, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FURY_ATTACK, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.KINGLER: PokemonData(pokemon=Pokemon.KINGLER, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=60, base_exp=206, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.VICEGRIP, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BLIZZARD, Move.BUBBLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.WATER_GUN, Move.HYPER_BEAM, Move.ICE_BEAM, Move.LEER, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.CHARMANDER: PokemonData(pokemon=Pokemon.CHARMANDER, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=45, base_exp=65, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.COUNTER, Move.TOXIC, Move.GROWL, Move.FIRE_BLAST, Move.MEGA_KICK, Move.SCRATCH, Move.DRAGON_RAGE, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWORDS_DANCE, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.CATERPIE: PokemonData(pokemon=Pokemon.CATERPIE, types=(FixedPokemonType.BUG, FixedPokemonType.BUG), catch_rate=255, base_exp=53, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.TACKLE, Move.STRING_SHOT, Move.NO_MOVE}),
    Pokemon.ALAKAZAM: PokemonData(pokemon=Pokemon.ALAKAZAM, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=50, base_exp=186, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.CONFUSION, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DISABLE, Move.DIG, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.ZUBAT: PokemonData(pokemon=Pokemon.ZUBAT, types=(FixedPokemonType.POISON, FixedPokemonType.FLYING), catch_rate=255, base_exp=54, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.LEECH_LIFE, Move.TAKE_DOWN, Move.MEGA_DRAIN, Move.MIMIC, Move.RAZOR_WIND, Move.DOUBLE_EDGE, Move.REST, Move.WHIRLWIND, Move.SWIFT, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.ARCANINE: PokemonData(pokemon=Pokemon.ARCANINE, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=75, base_exp=213, exp_growth=GrowthRate.SLOW, move_set={Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.TAKE_DOWN, Move.LEER, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.ROAR}),
    Pokemon.FEAROW: PokemonData(pokemon=Pokemon.FEAROW, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=90, base_exp=162, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.PECK, Move.GROWL, Move.HYPER_BEAM, Move.LEER, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.VULPIX: PokemonData(pokemon=Pokemon.VULPIX, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=190, base_exp=63, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.TAIL_WHIP, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.TANGELA: PokemonData(pokemon=Pokemon.TANGELA, types=(FixedPokemonType.GRASS, FixedPokemonType.GRASS), catch_rate=45, base_exp=166, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BIND, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.TOXIC, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.CONSTRICT}),
    Pokemon.WEEPINBELL: PokemonData(pokemon=Pokemon.WEEPINBELL, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=120, base_exp=151, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.GROWTH, Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.VINE_WHIP, Move.WRAP, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.MEWTWO: PokemonData(pokemon=Pokemon.MEWTWO, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=3, base_exp=220, exp_growth=GrowthRate.SLOW, move_set={Move.PSYCHIC_M, Move.CONFUSION, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.DISABLE, Move.REST, Move.SWIFT, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.PARAS: PokemonData(pokemon=Pokemon.PARAS, types=(FixedPokemonType.BUG, FixedPokemonType.GRASS), catch_rate=190, base_exp=70, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.WEEDLE: PokemonData(pokemon=Pokemon.WEEDLE, types=(FixedPokemonType.BUG, FixedPokemonType.POISON), catch_rate=255, base_exp=52, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.NO_MOVE, Move.STRING_SHOT, Move.POISON_STING}),
    Pokemon.GOLDUCK: PokemonData(pokemon=Pokemon.GOLDUCK, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=75, base_exp=174, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.COUNTER, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.SCRATCH, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DISABLE, Move.DIG, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.DEWGONG: PokemonData(pokemon=Pokemon.DEWGONG, types=(FixedPokemonType.WATER, FixedPokemonType.ICE), catch_rate=75, base_exp=176, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.AURORA_BEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.HEADBUTT, Move.GROWL, Move.HYPER_BEAM, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.NIDOQUEEN: PokemonData(pokemon=Pokemon.NIDOQUEEN, types=(FixedPokemonType.POISON, FixedPokemonType.GROUND), catch_rate=45, base_exp=194, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.ROCK_SLIDE, Move.BLIZZARD, Move.TACKLE, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.HYPER_BEAM, Move.MEGA_KICK, Move.SCRATCH, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.PORYGON: PokemonData(pokemon=Pokemon.PORYGON, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=45, base_exp=130, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.PSYCHIC_M, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TRI_ATTACK, Move.CONVERSION, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.THUNDER_WAVE, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.BIDE, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.SHARPEN, Move.TELEPORT, Move.FLASH}),
    Pokemon.MAROWAK: PokemonData(pokemon=Pokemon.MAROWAK, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=75, base_exp=124, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.GROWL, Move.HYPER_BEAM, Move.MEGA_KICK, Move.FIRE_BLAST, Move.TOXIC, Move.ICE_BEAM, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.FOCUS_ENERGY, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.BONE_CLUB}),
    Pokemon.ELECTABUZZ: PokemonData(pokemon=Pokemon.ELECTABUZZ, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=45, base_exp=156, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.PSYWAVE, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.MEGA_KICK, Move.THUNDER, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.MAGNEMITE: PokemonData(pokemon=Pokemon.MAGNEMITE, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=190, base_exp=89, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.THUNDERBOLT, Move.RAGE, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.REFLECT, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.EEVEE: PokemonData(pokemon=Pokemon.EEVEE, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=45, base_exp=92, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SAND_ATTACK, Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.CHANSEY: PokemonData(pokemon=Pokemon.CHANSEY, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=30, base_exp=255, exp_growth=GrowthRate.FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.EGG_BOMB, Move.POUND, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.DOUBLESLAP, Move.REST, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.SOFTBOILED, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.RATICATE: PokemonData(pokemon=Pokemon.RATICATE, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=90, base_exp=116, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.HAUNTER: PokemonData(pokemon=Pokemon.HAUNTER, types=(FixedPokemonType.GHOST, FixedPokemonType.POISON), catch_rate=90, base_exp=126, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.PSYCHIC_M, Move.MEGA_DRAIN, Move.NIGHT_SHADE, Move.MIMIC, Move.EXPLOSION, Move.THUNDERBOLT, Move.PSYWAVE, Move.DREAM_EATER, Move.RAGE, Move.DOUBLE_TEAM, Move.SELFDESTRUCT, Move.THUNDER, Move.CONFUSE_RAY, Move.REST, Move.LICK, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.CLEFAIRY: PokemonData(pokemon=Pokemon.CLEFAIRY, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=150, base_exp=68, exp_growth=GrowthRate.FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.POUND, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.GROWL, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.STARYU: PokemonData(pokemon=Pokemon.STARYU, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=225, base_exp=106, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TRI_ATTACK, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.WATER_GUN, Move.TOXIC, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.CLEFABLE: PokemonData(pokemon=Pokemon.CLEFABLE, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=25, base_exp=129, exp_growth=GrowthRate.FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.SING, Move.DOUBLESLAP, Move.REST, Move.SKULL_BASH, Move.TELEPORT, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.MINIMIZE, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.VICTREEBEL: PokemonData(pokemon=Pokemon.VICTREEBEL, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=45, base_exp=191, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.RAZOR_LEAF, Move.SLEEP_POWDER, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.STUN_SPORE, Move.SUBSTITUTE, Move.ACID, Move.BIDE}),
    Pokemon.GOLDEEN: PokemonData(pokemon=Pokemon.GOLDEEN, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=225, base_exp=111, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TAIL_WHIP, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.PECK, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.SNORLAX: PokemonData(pokemon=Pokemon.SNORLAX, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=25, base_exp=154, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.ROCK_SLIDE, Move.BLIZZARD, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.SOLARBEAM, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.HEADBUTT, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.AMNESIA, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.ARBOK: PokemonData(pokemon=Pokemon.ARBOK, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=90, base_exp=147, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.ROCK_SLIDE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.TOXIC, Move.EARTHQUAKE, Move.POISON_STING, Move.HYPER_BEAM, Move.WRAP, Move.LEER, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.HORSEA: PokemonData(pokemon=Pokemon.HORSEA, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=225, base_exp=83, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BUBBLE, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.GOLBAT: PokemonData(pokemon=Pokemon.GOLBAT, types=(FixedPokemonType.POISON, FixedPokemonType.FLYING), catch_rate=90, base_exp=171, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.BITE, Move.LEECH_LIFE, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.SCREECH, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.FARFETCHD: PokemonData(pokemon=Pokemon.FARFETCHD, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=45, base_exp=94, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SAND_ATTACK, Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.WHIRLWIND, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.PECK, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWORDS_DANCE, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.POLIWAG: PokemonData(pokemon=Pokemon.POLIWAG, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=255, base_exp=77, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BUBBLE, Move.BODY_SLAM, Move.PSYWAVE, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.DUGTRIO: PokemonData(pokemon=Pokemon.DUGTRIO, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=50, base_exp=153, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.ROCK_SLIDE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.EARTHQUAKE, Move.GROWL, Move.HYPER_BEAM, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.CHARIZARD: PokemonData(pokemon=Pokemon.CHARIZARD, types=(FixedPokemonType.FIRE, FixedPokemonType.FLYING), catch_rate=45, base_exp=209, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.COUNTER, Move.EARTHQUAKE, Move.TOXIC, Move.GROWL, Move.HYPER_BEAM, Move.MEGA_KICK, Move.FIRE_BLAST, Move.SCRATCH, Move.DRAGON_RAGE, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.SWORDS_DANCE, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.CLOYSTER: PokemonData(pokemon=Pokemon.CLOYSTER, types=(FixedPokemonType.WATER, FixedPokemonType.ICE), catch_rate=60, base_exp=203, exp_growth=GrowthRate.SLOW, move_set={Move.WITHDRAW, Move.SURF, Move.AURORA_BEAM, Move.SUPERSONIC, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TRI_ATTACK, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.HYPER_BEAM, Move.SELFDESTRUCT, Move.ICE_BEAM, Move.TAKE_DOWN, Move.CLAMP, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.KADABRA: PokemonData(pokemon=Pokemon.KADABRA, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=100, base_exp=145, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.CONFUSION, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DISABLE, Move.DIG, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.MR_MIME: PokemonData(pokemon=Pokemon.MR_MIME, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=45, base_exp=136, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.CONFUSION, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BARRIER, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.PSYWAVE, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.MEW: PokemonData(pokemon=Pokemon.MEW, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=45, base_exp=64, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.EGG_BOMB, Move.FLY, Move.POUND, Move.ROCK_SLIDE, Move.CUT, Move.BLIZZARD, Move.DREAM_EATER, Move.METRONOME, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.RAZOR_WIND, Move.REST, Move.FISSURE, Move.SWIFT, Move.SKULL_BASH, Move.TELEPORT, Move.SKY_ATTACK, Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.WHIRLWIND, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.DRAGON_RAGE, Move.ICE_BEAM, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.SOFTBOILED, Move.SWORDS_DANCE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.FLASH}),
    Pokemon.PRIMEAPE: PokemonData(pokemon=Pokemon.PRIMEAPE, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=75, base_exp=149, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.FURY_SWIPES, Move.COUNTER, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.SCRATCH, Move.THUNDER, Move.KARATE_CHOP, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.DODRIO: PokemonData(pokemon=Pokemon.DODRIO, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=45, base_exp=158, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.FLY, Move.FURY_ATTACK, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.PECK, Move.GROWL, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.EXEGGUTOR: PokemonData(pokemon=Pokemon.EXEGGUTOR, types=(FixedPokemonType.GRASS, FixedPokemonType.PSYCHIC_TYPE), catch_rate=45, base_exp=212, exp_growth=GrowthRate.SLOW, move_set={Move.SOLARBEAM, Move.PSYCHIC_M, Move.EGG_BOMB, Move.MEGA_DRAIN, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.RAGE, Move.PSYWAVE, Move.DOUBLE_TEAM, Move.REFLECT, Move.HYPNOSIS, Move.HYPER_BEAM, Move.SELFDESTRUCT, Move.TAKE_DOWN, Move.REST, Move.BARRAGE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.RHYHORN: PokemonData(pokemon=Pokemon.RHYHORN, types=(FixedPokemonType.GROUND, FixedPokemonType.ROCK), catch_rate=120, base_exp=135, exp_growth=GrowthRate.SLOW, move_set={Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.EARTHQUAKE, Move.TOXIC, Move.FIRE_BLAST, Move.THUNDER, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.HORN_ATTACK, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.VENONAT: PokemonData(pokemon=Pokemon.VENONAT, types=(FixedPokemonType.BUG, FixedPokemonType.POISON), catch_rate=190, base_exp=75, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.PSYCHIC_M, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.RAGE, Move.PSYWAVE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TAKE_DOWN, Move.DISABLE, Move.REST, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.SEADRA: PokemonData(pokemon=Pokemon.SEADRA, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=75, base_exp=155, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BUBBLE, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.HYPER_BEAM, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SMOKESCREEN, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.MANKEY: PokemonData(pokemon=Pokemon.MANKEY, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=190, base_exp=74, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.METRONOME, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.SCRATCH, Move.THUNDER, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.HITMONLEE: PokemonData(pokemon=Pokemon.HITMONLEE, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=45, base_exp=139, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.DOUBLE_KICK, Move.MEDITATE}),
    Pokemon.NIDOKING: PokemonData(pokemon=Pokemon.NIDOKING, types=(FixedPokemonType.POISON, FixedPokemonType.GROUND), catch_rate=45, base_exp=195, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.THRASH, Move.SEISMIC_TOSS, Move.ROCK_SLIDE, Move.BLIZZARD, Move.TACKLE, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.POISON_STING, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.PAY_DAY, Move.HORN_ATTACK, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.MEOWTH: PokemonData(pokemon=Pokemon.MEOWTH, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=255, base_exp=69, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.GROWL, Move.SCRATCH, Move.THUNDER, Move.TAKE_DOWN, Move.PAY_DAY, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.MOLTRES: PokemonData(pokemon=Pokemon.MOLTRES, types=(FixedPokemonType.FIRE, FixedPokemonType.FLYING), catch_rate=3, base_exp=217, exp_growth=GrowthRate.SLOW, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.PECK, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.FIRE_SPIN, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.BLASTOISE: PokemonData(pokemon=Pokemon.BLASTOISE, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=45, base_exp=210, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.BUBBLE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.COUNTER, Move.EARTHQUAKE, Move.HYPER_BEAM, Move.MEGA_KICK, Move.TOXIC, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.OMASTAR: PokemonData(pokemon=Pokemon.OMASTAR, types=(FixedPokemonType.ROCK, FixedPokemonType.WATER), catch_rate=45, base_exp=199, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.WITHDRAW, Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.HORN_ATTACK, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.SANDSHREW: PokemonData(pokemon=Pokemon.SANDSHREW, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=255, base_exp=93, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.CUT, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.EARTHQUAKE, Move.TOXIC, Move.SCRATCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.SWORDS_DANCE, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.BELLSPROUT: PokemonData(pokemon=Pokemon.BELLSPROUT, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=255, base_exp=84, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.GROWTH, Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.VINE_WHIP, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.PSYDUCK: PokemonData(pokemon=Pokemon.PSYDUCK, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=190, base_exp=80, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.COUNTER, Move.WATER_GUN, Move.TOXIC, Move.MEGA_KICK, Move.SCRATCH, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.METAPOD: PokemonData(pokemon=Pokemon.METAPOD, types=(FixedPokemonType.BUG, FixedPokemonType.BUG), catch_rate=120, base_exp=72, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.HARDEN, Move.NO_MOVE}),
    Pokemon.SQUIRTLE: PokemonData(pokemon=Pokemon.SQUIRTLE, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=45, base_exp=66, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.COUNTER, Move.WATER_GUN, Move.TOXIC, Move.MEGA_KICK, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.NIDORANF: PokemonData(pokemon=Pokemon.NIDORANF, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=235, base_exp=59, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.GROWL, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.RHYDON: PokemonData(pokemon=Pokemon.RHYDON, types=(FixedPokemonType.GROUND, FixedPokemonType.ROCK), catch_rate=60, base_exp=204, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.ROCK_SLIDE, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.FURY_ATTACK, Move.MIMIC, Move.STOMP, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.TAIL_WHIP, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.DIG, Move.PAY_DAY, Move.HORN_ATTACK, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.TENTACOOL: PokemonData(pokemon=Pokemon.TENTACOOL, types=(FixedPokemonType.WATER, FixedPokemonType.POISON), catch_rate=190, base_exp=105, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SKULL_BASH, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BLIZZARD, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.ACID, Move.BIDE}),
    Pokemon.LICKITUNG: PokemonData(pokemon=Pokemon.LICKITUNG, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=45, base_exp=127, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SUPERSONIC, Move.SEISMIC_TOSS, Move.CUT, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.HYPER_BEAM, Move.MEGA_KICK, Move.WRAP, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.SWORDS_DANCE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.DRAGONITE: PokemonData(pokemon=Pokemon.DRAGONITE, types=(FixedPokemonType.DRAGON, FixedPokemonType.FLYING), catch_rate=45, base_exp=218, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SKULL_BASH, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.WRAP, Move.THUNDER, Move.ICE_BEAM, Move.LEER, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.AGILITY, Move.BIDE}),
    Pokemon.TAUROS: PokemonData(pokemon=Pokemon.TAUROS, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=45, base_exp=211, exp_growth=GrowthRate.SLOW, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.EARTHQUAKE, Move.TOXIC, Move.HYPER_BEAM, Move.FIRE_BLAST, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.CHARMELEON: PokemonData(pokemon=Pokemon.CHARMELEON, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=45, base_exp=142, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.REFLECT, Move.COUNTER, Move.TOXIC, Move.GROWL, Move.FIRE_BLAST, Move.MEGA_KICK, Move.SCRATCH, Move.DRAGON_RAGE, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWORDS_DANCE, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.ONIX: PokemonData(pokemon=Pokemon.ONIX, types=(FixedPokemonType.ROCK, FixedPokemonType.GROUND), catch_rate=45, base_exp=108, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.ROCK_SLIDE, Move.TACKLE, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.TOXIC, Move.EARTHQUAKE, Move.SCREECH, Move.SELFDESTRUCT, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.ABRA: PokemonData(pokemon=Pokemon.ABRA, types=(FixedPokemonType.PSYCHIC_TYPE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=200, base_exp=73, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.TRI_ATTACK, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.REFLECT, Move.THUNDER_WAVE, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.ARTICUNO: PokemonData(pokemon=Pokemon.ARTICUNO, types=(FixedPokemonType.ICE, FixedPokemonType.FLYING), catch_rate=3, base_exp=215, exp_growth=GrowthRate.SLOW, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.PECK, Move.HYPER_BEAM, Move.ICE_BEAM, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK}),
    Pokemon.BUTTERFREE: PokemonData(pokemon=Pokemon.BUTTERFREE, types=(FixedPokemonType.BUG, FixedPokemonType.FLYING), catch_rate=45, base_exp=160, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SOLARBEAM, Move.CONFUSION, Move.PSYCHIC_M, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.PSYWAVE, Move.DOUBLE_TEAM, Move.REFLECT, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.MACHAMP: PokemonData(pokemon=Pokemon.MACHAMP, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=45, base_exp=193, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.LOW_KICK, Move.FIRE_BLAST, Move.KARATE_CHOP, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.PINSIR: PokemonData(pokemon=Pokemon.PINSIR, types=(FixedPokemonType.BUG, FixedPokemonType.BUG), catch_rate=45, base_exp=200, exp_growth=GrowthRate.SLOW, move_set={Move.VICEGRIP, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.HYPER_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.CUBONE: PokemonData(pokemon=Pokemon.CUBONE, types=(FixedPokemonType.GROUND, FixedPokemonType.GROUND), catch_rate=190, base_exp=87, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.BUBBLEBEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.GROWL, Move.FIRE_BLAST, Move.MEGA_KICK, Move.TOXIC, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.BONE_CLUB}),
    Pokemon.VOLTORB: PokemonData(pokemon=Pokemon.VOLTORB, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=190, base_exp=103, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.EXPLOSION, Move.TACKLE, Move.THUNDERBOLT, Move.RAGE, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.REFLECT, Move.SCREECH, Move.SELFDESTRUCT, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.STARMIE: PokemonData(pokemon=Pokemon.STARMIE, types=(FixedPokemonType.WATER, FixedPokemonType.PSYCHIC_TYPE), catch_rate=60, base_exp=207, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SKULL_BASH, Move.PSYCHIC_M, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TRI_ATTACK, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.THUNDER_WAVE, Move.TOXIC, Move.HYPER_BEAM, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.HARDEN, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.GEODUDE: PokemonData(pokemon=Pokemon.GEODUDE, types=(FixedPokemonType.ROCK, FixedPokemonType.GROUND), catch_rate=255, base_exp=86, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.EXPLOSION, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.FIRE_BLAST, Move.SELFDESTRUCT, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.DRATINI: PokemonData(pokemon=Pokemon.DRATINI, types=(FixedPokemonType.DRAGON, FixedPokemonType.DRAGON), catch_rate=45, base_exp=67, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.THUNDER_WAVE, Move.WATER_GUN, Move.TOXIC, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.WRAP, Move.THUNDER, Move.LEER, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.ODDISH: PokemonData(pokemon=Pokemon.ODDISH, types=(FixedPokemonType.GRASS, FixedPokemonType.POISON), catch_rate=255, base_exp=78, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SOLARBEAM, Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.ABSORB, Move.REFLECT, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.HITMONCHAN: PokemonData(pokemon=Pokemon.HITMONCHAN, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=45, base_exp=140, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.COMET_PUNCH, Move.SKULL_BASH, Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.TOXIC, Move.MEGA_KICK, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SWIFT, Move.SUBSTITUTE, Move.AGILITY, Move.BIDE}),
    Pokemon.MAGNETON: PokemonData(pokemon=Pokemon.MAGNETON, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=60, base_exp=161, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.TACKLE, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.REFLECT, Move.HYPER_BEAM, Move.THUNDER, Move.SUBSTITUTE, Move.TAKE_DOWN, Move.SONICBOOM, Move.REST, Move.SWIFT, Move.THUNDERSHOCK, Move.TOXIC, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.ZAPDOS: PokemonData(pokemon=Pokemon.ZAPDOS, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.FLYING), catch_rate=3, base_exp=216, exp_growth=GrowthRate.SLOW, move_set={Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.FLASH, Move.THUNDER_WAVE, Move.REFLECT, Move.HYPER_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.SUBSTITUTE, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.THUNDERSHOCK, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK, Move.DRILL_PECK}),
    Pokemon.KAKUNA: PokemonData(pokemon=Pokemon.KAKUNA, types=(FixedPokemonType.BUG, FixedPokemonType.POISON), catch_rate=120, base_exp=71, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.HARDEN, Move.NO_MOVE}),
    Pokemon.SEAKING: PokemonData(pokemon=Pokemon.SEAKING, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=60, base_exp=170, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SUPERSONIC, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TAIL_WHIP, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.TOXIC, Move.WATER_GUN, Move.PECK, Move.HYPER_BEAM, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.JYNX: PokemonData(pokemon=Pokemon.JYNX, types=(FixedPokemonType.ICE, FixedPokemonType.PSYCHIC_TYPE), catch_rate=45, base_exp=137, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.PSYCHIC_M, Move.SEISMIC_TOSS, Move.POUND, Move.MIMIC, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.PSYWAVE, Move.SUBMISSION, Move.BUBBLEBEAM, Move.REFLECT, Move.COUNTER, Move.WATER_GUN, Move.TOXIC, Move.HYPER_BEAM, Move.MEGA_KICK, Move.ICE_BEAM, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.LOVELY_KISS, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT}),
    Pokemon.SCYTHER: PokemonData(pokemon=Pokemon.SCYTHER, types=(FixedPokemonType.BUG, FixedPokemonType.FLYING), catch_rate=45, base_exp=187, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.RAGE, Move.DOUBLE_TEAM, Move.TOXIC, Move.HYPER_BEAM, Move.QUICK_ATTACK, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.LAPRAS: PokemonData(pokemon=Pokemon.LAPRAS, types=(FixedPokemonType.WATER, FixedPokemonType.ICE), catch_rate=45, base_exp=219, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.SOLARBEAM, Move.PSYCHIC_M, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.PSYWAVE, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.GROWL, Move.HYPER_BEAM, Move.DRAGON_RAGE, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.ELECTRODE: PokemonData(pokemon=Pokemon.ELECTRODE, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=60, base_exp=150, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.EXPLOSION, Move.TACKLE, Move.THUNDERBOLT, Move.RAGE, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.REFLECT, Move.TOXIC, Move.SCREECH, Move.HYPER_BEAM, Move.SELFDESTRUCT, Move.THUNDER, Move.TAKE_DOWN, Move.SONICBOOM, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.TELEPORT, Move.FLASH}),
    Pokemon.DRAGONAIR: PokemonData(pokemon=Pokemon.DRAGONAIR, types=(FixedPokemonType.DRAGON, FixedPokemonType.DRAGON), catch_rate=45, base_exp=144, exp_growth=GrowthRate.SLOW, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.THUNDER_WAVE, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.WRAP, Move.THUNDER, Move.LEER, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.EKANS: PokemonData(pokemon=Pokemon.EKANS, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=255, base_exp=62, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MEGA_DRAIN, Move.MIMIC, Move.DOUBLE_EDGE, Move.ROCK_SLIDE, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.TOXIC, Move.EARTHQUAKE, Move.WRAP, Move.LEER, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.GROWLITHE: PokemonData(pokemon=Pokemon.GROWLITHE, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=190, base_exp=91, exp_growth=GrowthRate.SLOW, move_set={Move.BITE, Move.MIMIC, Move.DOUBLE_EDGE, Move.RAGE, Move.BODY_SLAM, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.FIRE_BLAST, Move.DRAGON_RAGE, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE, Move.ROAR}),
    Pokemon.KRABBY: PokemonData(pokemon=Pokemon.KRABBY, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=225, base_exp=115, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.MIMIC, Move.DOUBLE_EDGE, Move.CUT, Move.BLIZZARD, Move.BUBBLE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.WATER_GUN, Move.ICE_BEAM, Move.LEER, Move.TAKE_DOWN, Move.REST, Move.SWORDS_DANCE, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.KANGASKHAN: PokemonData(pokemon=Pokemon.KANGASKHAN, types=(FixedPokemonType.NORMAL, FixedPokemonType.NORMAL), catch_rate=45, base_exp=175, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SURF, Move.SEISMIC_TOSS, Move.ROCK_SLIDE, Move.BLIZZARD, Move.SUBMISSION, Move.BUBBLEBEAM, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.REST, Move.FISSURE, Move.SKULL_BASH, Move.COMET_PUNCH, Move.MIMIC, Move.DOUBLE_EDGE, Move.RAGE, Move.BODY_SLAM, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.COUNTER, Move.EARTHQUAKE, Move.WATER_GUN, Move.FIRE_BLAST, Move.ICE_BEAM, Move.TAKE_DOWN, Move.STRENGTH, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.RAICHU: PokemonData(pokemon=Pokemon.RAICHU, types=(FixedPokemonType.ELECTRIC, FixedPokemonType.ELECTRIC), catch_rate=75, base_exp=122, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.SUBMISSION, Move.THUNDER_WAVE, Move.REFLECT, Move.TOXIC, Move.GROWL, Move.HYPER_BEAM, Move.MEGA_KICK, Move.THUNDER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.SUBSTITUTE, Move.PAY_DAY, Move.REST, Move.SWIFT, Move.THUNDERSHOCK, Move.SKULL_BASH, Move.BIDE, Move.FLASH}),
    Pokemon.PONYTA: PokemonData(pokemon=Pokemon.PONYTA, types=(FixedPokemonType.FIRE, FixedPokemonType.FIRE), catch_rate=190, base_exp=152, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.EMBER, Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TOXIC, Move.FIRE_BLAST, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.SHELLDER: PokemonData(pokemon=Pokemon.SHELLDER, types=(FixedPokemonType.WATER, FixedPokemonType.WATER), catch_rate=190, base_exp=97, exp_growth=GrowthRate.SLOW, move_set={Move.WITHDRAW, Move.SURF, Move.MIMIC, Move.EXPLOSION, Move.DOUBLE_EDGE, Move.BLIZZARD, Move.TACKLE, Move.TRI_ATTACK, Move.RAGE, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.SELFDESTRUCT, Move.ICE_BEAM, Move.TAKE_DOWN, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.TELEPORT}),
    Pokemon.MACHOP: PokemonData(pokemon=Pokemon.MACHOP, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=180, base_exp=88, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.TOXIC, Move.FIRE_BLAST, Move.MEGA_KICK, Move.KARATE_CHOP, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.NIDORINA: PokemonData(pokemon=Pokemon.NIDORINA, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=120, base_exp=117, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.MIMIC, Move.DOUBLE_EDGE, Move.HORN_DRILL, Move.BLIZZARD, Move.TACKLE, Move.BODY_SLAM, Move.RAGE, Move.THUNDERBOLT, Move.DOUBLE_TEAM, Move.BUBBLEBEAM, Move.REFLECT, Move.WATER_GUN, Move.TOXIC, Move.GROWL, Move.SCRATCH, Move.ICE_BEAM, Move.THUNDER, Move.TAKE_DOWN, Move.REST, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.MACHOKE: PokemonData(pokemon=Pokemon.MACHOKE, types=(FixedPokemonType.FIGHTING, FixedPokemonType.FIGHTING), catch_rate=90, base_exp=146, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SEISMIC_TOSS, Move.MIMIC, Move.ROCK_SLIDE, Move.DOUBLE_EDGE, Move.BODY_SLAM, Move.RAGE, Move.DOUBLE_TEAM, Move.METRONOME, Move.SUBMISSION, Move.COUNTER, Move.EARTHQUAKE, Move.TOXIC, Move.FIRE_BLAST, Move.MEGA_KICK, Move.LOW_KICK, Move.KARATE_CHOP, Move.LEER, Move.MEGA_PUNCH, Move.TAKE_DOWN, Move.DIG, Move.REST, Move.FISSURE, Move.STRENGTH, Move.SUBSTITUTE, Move.SKULL_BASH, Move.BIDE}),
    Pokemon.WEEZING: PokemonData(pokemon=Pokemon.WEEZING, types=(FixedPokemonType.POISON, FixedPokemonType.POISON), catch_rate=60, base_exp=173, exp_growth=GrowthRate.MEDIUM_FAST, move_set={Move.MIMIC, Move.EXPLOSION, Move.TACKLE, Move.THUNDERBOLT, Move.RAGE, Move.DOUBLE_TEAM, Move.HYPER_BEAM, Move.SELFDESTRUCT, Move.FIRE_BLAST, Move.THUNDER, Move.REST, Move.SMOG, Move.SLUDGE, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE}),
    Pokemon.PIDGEOTTO: PokemonData(pokemon=Pokemon.PIDGEOTTO, types=(FixedPokemonType.NORMAL, FixedPokemonType.FLYING), catch_rate=120, base_exp=113, exp_growth=GrowthRate.MEDIUM_SLOW, move_set={Move.SAND_ATTACK, Move.FLY, Move.MIMIC, Move.DOUBLE_EDGE, Move.WHIRLWIND, Move.RAGE, Move.DOUBLE_TEAM, Move.REFLECT, Move.TAKE_DOWN, Move.RAZOR_WIND, Move.REST, Move.SWIFT, Move.SUBSTITUTE, Move.TOXIC, Move.BIDE, Move.SKY_ATTACK, Move.GUST}),
}
