from typing import NamedTuple

from deepred.polaris_env.pokemon_red.enums import BagItem


class BagItemInfo(NamedTuple):
    price: int
    priority: int = 0 # used to rank items when it comes to selling, buying, tossing. key items should never be tossed.

    @property
    def sell_price(self) -> int:
        return self.price // 2


key_item = int(1e8)


BagItemsInfo = {
    BagItem.MASTER_BALL: BagItemInfo(price=0, priority=10),
    BagItem.ULTRA_BALL: BagItemInfo(price=1200, priority=9),
    BagItem.GREAT_BALL: BagItemInfo(price=600, priority=8),
    BagItem.POKE_BALL: BagItemInfo(price=200, priority=7),
    BagItem.TOWN_MAP: BagItemInfo(price=0, priority=key_item),
    BagItem.BICYCLE: BagItemInfo(price=0, priority=key_item),
    BagItem.SURFBOARD: BagItemInfo(price=0, priority=key_item),
    BagItem.SAFARI_BALL: BagItemInfo(price=1000, priority=key_item), # should not be able to be tossed.
    BagItem.POKEDEX: BagItemInfo(price=0, priority=key_item),
    BagItem.MOON_STONE: BagItemInfo(price=0),
    BagItem.ANTIDOTE: BagItemInfo(price=100),
    BagItem.BURN_HEAL: BagItemInfo(price=250),
    BagItem.ICE_HEAL: BagItemInfo(price=250),
    BagItem.AWAKENING: BagItemInfo(price=200),
    BagItem.PARLYZ_HEAL: BagItemInfo(price=200),
    BagItem.FULL_RESTORE: BagItemInfo(price=3000, priority=9),
    BagItem.MAX_POTION: BagItemInfo(price=2500, priority=8),
    BagItem.HYPER_POTION: BagItemInfo(price=1500, priority=7),
    BagItem.SUPER_POTION: BagItemInfo(price=700, priority=6),
    BagItem.POTION: BagItemInfo(price=300, priority=5),
    BagItem.BOULDERBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.CASCADEBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.THUNDERBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.RAINBOWBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.SOULBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.MARSHBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.VOLCANOBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.EARTHBADGE: BagItemInfo(price=0, priority=key_item),
    BagItem.ESCAPE_ROPE: BagItemInfo(price=550),
    BagItem.REPEL: BagItemInfo(price=350),
    BagItem.OLD_AMBER: BagItemInfo(price=0, priority=key_item),
    BagItem.FIRE_STONE: BagItemInfo(price=2100),
    BagItem.THUNDER_STONE: BagItemInfo(price=2100),
    BagItem.WATER_STONE: BagItemInfo(price=2100),
    BagItem.HP_UP: BagItemInfo(price=9800),
    BagItem.PROTEIN: BagItemInfo(price=9800),
    BagItem.IRON: BagItemInfo(price=9800),
    BagItem.CARBOS: BagItemInfo(price=9800),
    BagItem.CALCIUM: BagItemInfo(price=9800),
    BagItem.RARE_CANDY: BagItemInfo(price=4800),
    BagItem.DOME_FOSSIL: BagItemInfo(price=0, priority=key_item),
    BagItem.HELIX_FOSSIL: BagItemInfo(price=0, priority=key_item),
    BagItem.SECRET_KEY: BagItemInfo(price=0, priority=key_item),
    BagItem.ITEM_2C: BagItemInfo(price=9800),
    BagItem.BIKE_VOUCHER: BagItemInfo(price=0, priority=key_item),
    BagItem.X_ACCURACY: BagItemInfo(price=950),
    BagItem.LEAF_STONE: BagItemInfo(price=2100),
    BagItem.CARD_KEY: BagItemInfo(price=0, priority=key_item),
    BagItem.NUGGET: BagItemInfo(price=10000),
    BagItem.POKE_DOLL: BagItemInfo(price=1000),
    BagItem.FULL_HEAL: BagItemInfo(price=600, priority=2),
    BagItem.REVIVE: BagItemInfo(price=1500, priority=8),
    BagItem.MAX_REVIVE: BagItemInfo(price=4000, priority=9),
    BagItem.GUARD_SPEC: BagItemInfo(price=700),
    BagItem.SUPER_REPEL: BagItemInfo(price=500),
    BagItem.MAX_REPEL: BagItemInfo(price=700),
    BagItem.DIRE_HIT: BagItemInfo(price=650),
    BagItem.COIN: BagItemInfo(price=10),
    BagItem.FRESH_WATER: BagItemInfo(price=200, priority=key_item),
    BagItem.SODA_POP: BagItemInfo(price=300),
    BagItem.LEMONADE: BagItemInfo(price=350),
    BagItem.SS_TICKET: BagItemInfo(price=0, priority=key_item),
    BagItem.GOLD_TEETH: BagItemInfo(price=0, priority=key_item),
    BagItem.X_ATTACK: BagItemInfo(price=500),
    BagItem.X_DEFEND: BagItemInfo(price=550),
    BagItem.X_SPEED: BagItemInfo(price=350),
    BagItem.X_SPECIAL: BagItemInfo(price=350),
    BagItem.COIN_CASE: BagItemInfo(price=0, priority=key_item),
    BagItem.OAKS_PARCEL: BagItemInfo(price=0, priority=key_item),
    BagItem.ITEMFINDER: BagItemInfo(price=0, priority=key_item),
    BagItem.SILPH_SCOPE: BagItemInfo(price=0, priority=key_item),
    BagItem.POKE_FLUTE: BagItemInfo(price=0, priority=key_item),
    BagItem.LIFT_KEY: BagItemInfo(price=0, priority=key_item),
    BagItem.EXP_ALL: BagItemInfo(price=0, priority=key_item),
    BagItem.OLD_ROD: BagItemInfo(price=0, priority=key_item),
    BagItem.GOOD_ROD: BagItemInfo(price=0, priority=key_item),
    BagItem.SUPER_ROD: BagItemInfo(price=0, priority=key_item),
    BagItem.PP_UP: BagItemInfo(price=0),
    BagItem.ETHER: BagItemInfo(price=0),
    BagItem.MAX_ETHER: BagItemInfo(price=0),
    BagItem.ELIXIR: BagItemInfo(price=0),
    BagItem.MAX_ELIXIR: BagItemInfo(price=0),
    BagItem.FLOOR_B2F: BagItemInfo(price=0),
    BagItem.FLOOR_B1F: BagItemInfo(price=0),
    BagItem.FLOOR_1F: BagItemInfo(price=0),
    BagItem.FLOOR_2F: BagItemInfo(price=0),
    BagItem.FLOOR_3F: BagItemInfo(price=0),
    BagItem.FLOOR_4F: BagItemInfo(price=0),
    BagItem.FLOOR_5F: BagItemInfo(price=0),
    BagItem.FLOOR_6F: BagItemInfo(price=0),
    BagItem.FLOOR_7F: BagItemInfo(price=0),
    BagItem.FLOOR_8F: BagItemInfo(price=0),
    BagItem.FLOOR_9F: BagItemInfo(price=0),
    BagItem.FLOOR_10F: BagItemInfo(price=0),
    BagItem.FLOOR_11F: BagItemInfo(price=0),
    BagItem.FLOOR_B4F: BagItemInfo(price=0),
    BagItem.HM_CUT: BagItemInfo(price=0, priority=key_item),
    BagItem.HM_FLY: BagItemInfo(price=0, priority=key_item),
    BagItem.HM_SURF: BagItemInfo(price=0, priority=key_item),
    BagItem.HM_STRENGTH: BagItemInfo(price=0, priority=key_item),
    BagItem.HM_FLASH: BagItemInfo(price=0, priority=key_item),
    BagItem.TM_MEGA_PUNCH: BagItemInfo(price=3000),
    BagItem.TM_RAZOR_WIND: BagItemInfo(price=2000),
    BagItem.TM_SWORDS_DANCE: BagItemInfo(price=2000),
    BagItem.TM_WHIRLWIND: BagItemInfo(price=1000),
    BagItem.TM_MEGA_KICK: BagItemInfo(price=3000),
    BagItem.TM_TOXIC: BagItemInfo(price=4000),
    BagItem.TM_HORN_DRILL: BagItemInfo(price=2000),
    BagItem.TM_BODY_SLAM: BagItemInfo(price=4000),
    BagItem.TM_TAKE_DOWN: BagItemInfo(price=3000),
    BagItem.TM_DOUBLE_EDGE: BagItemInfo(price=4000),
    BagItem.TM_BUBBLEBEAM: BagItemInfo(price=2000),
    BagItem.TM_WATER_GUN: BagItemInfo(price=1000),
    BagItem.TM_ICE_BEAM: BagItemInfo(price=4000),
    BagItem.TM_BLIZZARD: BagItemInfo(price=5000),
    BagItem.TM_HYPER_BEAM: BagItemInfo(price=5000),
    BagItem.TM_PAY_DAY: BagItemInfo(price=5000),
    BagItem.TM_SUBMISSION: BagItemInfo(price=3000),
    BagItem.TM_COUNTER: BagItemInfo(price=2000),
    BagItem.TM_SEISMIC_TOSS: BagItemInfo(price=3000),
    BagItem.TM_RAGE: BagItemInfo(price=2000),
    BagItem.TM_MEGA_DRAIN: BagItemInfo(price=5000),
    BagItem.TM_SOLARBEAM: BagItemInfo(price=5000),
    BagItem.TM_DRAGON_RAGE: BagItemInfo(price=5000),
    BagItem.TM_THUNDERBOLT: BagItemInfo(price=2000),
    BagItem.TM_THUNDER: BagItemInfo(price=5000),
    BagItem.TM_EARTHQUAKE: BagItemInfo(price=4000),
    BagItem.TM_FISSURE: BagItemInfo(price=5000),
    BagItem.TM_DIG: BagItemInfo(price=2000),
    BagItem.TM_PSYCHIC_M: BagItemInfo(price=4000),
    BagItem.TM_TELEPORT: BagItemInfo(price=1000),
    BagItem.TM_MIMIC: BagItemInfo(price=2000),
    BagItem.TM_DOUBLE_TEAM: BagItemInfo(price=1000),
    BagItem.TM_REFLECT: BagItemInfo(price=1000),
    BagItem.TM_BIDE: BagItemInfo(price=2000),
    BagItem.TM_METRONOME: BagItemInfo(price=4000),
    BagItem.TM_SELFDESTRUCT: BagItemInfo(price=2000),
    BagItem.TM_EGG_BOMB: BagItemInfo(price=2000),
    BagItem.TM_FIRE_BLAST: BagItemInfo(price=5000),
    BagItem.TM_SWIFT: BagItemInfo(price=2000),
    BagItem.TM_SKULL_BASH: BagItemInfo(price=4000),
    BagItem.TM_SOFTBOILED: BagItemInfo(price=2000),
    BagItem.TM_DREAM_EATER: BagItemInfo(price=2000),
    BagItem.TM_SKY_ATTACK: BagItemInfo(price=5000),
    BagItem.TM_REST: BagItemInfo(price=2000),
    BagItem.TM_THUNDER_WAVE: BagItemInfo(price=2000),
    BagItem.TM_PSYWAVE: BagItemInfo(price=4000),
    BagItem.TM_EXPLOSION: BagItemInfo(price=3000),
    BagItem.TM_ROCK_SLIDE: BagItemInfo(price=4000),
    BagItem.TM_TRI_ATTACK: BagItemInfo(price=4000),
    BagItem.TM_SUBSTITUTE: BagItemInfo(price=2000),

}