from typing import List

from typing_extensions import NamedTuple

from deepred.polaris_env.pokemon_red.enums import Map


class MapWarp:
    _instance_count = 0

    def __init__(
            self,
            x: int,
            y: int,
            id: int,
            destination: Map
    ):
        # Increment the counter each time an instance is created
        self._instance_number = MapWarp._instance_count
        MapWarp._instance_count += 1

        self.x = x
        self.y = y
        self.id = id
        self.destination = destination

    @property
    def global_id(self):
        return self._instance_number


MapWarps = {
    Map.AGATHAS_ROOM: [MapWarp(x=4, y=11, id=3, destination=Map.BRUNOS_ROOM), MapWarp(x=5, y=11, id=4, destination=Map.BRUNOS_ROOM), MapWarp(x=4, y=0, id=1, destination=Map.LANCES_ROOM), MapWarp(x=5, y=0, id=1, destination=Map.LANCES_ROOM)],
    Map.BIKE_SHOP: [MapWarp(x=2, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN)],
    Map.BILLS_HOUSE: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN)],
    Map.BLUES_HOUSE: [MapWarp(x=2, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=2, destination=Map.UNKNOWN)],
    Map.BRUNOS_ROOM: [MapWarp(x=4, y=11, id=3, destination=Map.LORELEIS_ROOM),MapWarp(x=5, y=11, id=4, destination=Map.LORELEIS_ROOM),MapWarp(x=4, y=0, id=1, destination=Map.AGATHAS_ROOM),MapWarp(x=5, y=0, id=2, destination=Map.AGATHAS_ROOM)],
    Map.CELADON_CHIEF_HOUSE: [MapWarp(x=2, y=7, id=12, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=12, destination=Map.UNKNOWN)],
    Map.CELADON_CITY: [MapWarp(x=8, y=13, id=1, destination=Map.CELADON_MART_1F),MapWarp(x=10, y=13, id=3, destination=Map.CELADON_MART_1F),MapWarp(x=24, y=9, id=1, destination=Map.CELADON_MANSION_1F),MapWarp(x=24, y=3, id=3, destination=Map.CELADON_MANSION_1F),MapWarp(x=25, y=3, id=3, destination=Map.CELADON_MANSION_1F),MapWarp(x=41, y=9, id=1, destination=Map.CELADON_POKECENTER),MapWarp(x=12, y=27, id=1, destination=Map.CELADON_GYM),MapWarp(x=28, y=19, id=1, destination=Map.GAME_CORNER),MapWarp(x=39, y=19, id=1, destination=Map.CELADON_MART_5F),MapWarp(x=33, y=19, id=1, destination=Map.GAME_CORNER_PRIZE_ROOM),MapWarp(x=31, y=27, id=1, destination=Map.CELADON_DINER),MapWarp(x=35, y=27, id=1, destination=Map.CELADON_CHIEF_HOUSE),MapWarp(x=43, y=27, id=1, destination=Map.CELADON_HOTEL)],
    Map.CELADON_DINER: [MapWarp(x=3, y=7, id=11, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=11, destination=Map.UNKNOWN)],
    Map.CELADON_GYM: [MapWarp(x=4, y=17, id=7, destination=Map.UNKNOWN),MapWarp(x=5, y=17, id=7, destination=Map.UNKNOWN)],
    Map.CELADON_HOTEL: [MapWarp(x=3, y=7, id=13, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=13, destination=Map.UNKNOWN)],
    Map.CELADON_MANSION_1F: [MapWarp(x=4, y=11, id=3, destination=Map.UNKNOWN),MapWarp(x=5, y=11, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=0, id=5, destination=Map.UNKNOWN),MapWarp(x=7, y=1, id=2, destination=Map.CELADON_MANSION_2F),MapWarp(x=2, y=1, id=3, destination=Map.CELADON_MANSION_2F)],
    Map.CELADON_MANSION_2F: [MapWarp(x=6, y=1, id=1, destination=Map.CELADON_MANSION_3F),MapWarp(x=7, y=1, id=4, destination=Map.CELADON_MANSION_1F),MapWarp(x=2, y=1, id=5, destination=Map.CELADON_MANSION_1F),MapWarp(x=4, y=1, id=4, destination=Map.CELADON_MANSION_3F)],
    Map.CELADON_MANSION_3F: [MapWarp(x=6, y=1, id=1, destination=Map.CELADON_MANSION_2F),MapWarp(x=7, y=1, id=1, destination=Map.CELADON_MANSION_ROOF),MapWarp(x=2, y=1, id=2, destination=Map.CELADON_MANSION_ROOF),MapWarp(x=4, y=1, id=4, destination=Map.CELADON_MANSION_2F)],
    Map.CELADON_MANSION_ROOF: [MapWarp(x=6, y=1, id=2, destination=Map.CELADON_MANSION_3F),MapWarp(x=2, y=1, id=3, destination=Map.CELADON_MANSION_3F),MapWarp(x=2, y=7, id=1, destination=Map.CELADON_MANSION_ROOF_HOUSE)],
    Map.CELADON_MANSION_ROOF_HOUSE: [MapWarp(x=2, y=7, id=3, destination=Map.CELADON_MANSION_ROOF),MapWarp(x=3, y=7, id=3, destination=Map.CELADON_MANSION_ROOF)],
    Map.CELADON_MART_1F: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=16, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=17, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=12, y=1, id=1, destination=Map.CELADON_MART_2F),MapWarp(x=1, y=1, id=1, destination=Map.CELADON_MART_ELEVATOR)],
    Map.CELADON_MART_2F: [MapWarp(x=12, y=1, id=5, destination=Map.CELADON_MART_1F),MapWarp(x=16, y=1, id=2, destination=Map.CELADON_MART_3F),MapWarp(x=1, y=1, id=1, destination=Map.CELADON_MART_ELEVATOR)],
    Map.CELADON_MART_3F: [MapWarp(x=12, y=1, id=1, destination=Map.CELADON_MART_4F),MapWarp(x=16, y=1, id=2, destination=Map.CELADON_MART_2F),MapWarp(x=1, y=1, id=1, destination=Map.CELADON_MART_ELEVATOR)],
    Map.CELADON_MART_4F: [MapWarp(x=12, y=1, id=1, destination=Map.CELADON_MART_3F),MapWarp(x=16, y=1, id=2, destination=Map.CELADON_MART_5F),MapWarp(x=1, y=1, id=1, destination=Map.CELADON_MART_ELEVATOR)],
    Map.CELADON_MART_5F: [MapWarp(x=12, y=1, id=1, destination=Map.CELADON_MART_ROOF),MapWarp(x=16, y=1, id=2, destination=Map.CELADON_MART_4F),MapWarp(x=1, y=1, id=1, destination=Map.CELADON_MART_ELEVATOR)],
    Map.CELADON_MART_ELEVATOR: [MapWarp(x=1, y=3, id=6, destination=Map.CELADON_MART_1F),MapWarp(x=2, y=3, id=6, destination=Map.CELADON_MART_1F)],
    Map.CELADON_MART_ROOF: [MapWarp(x=15, y=2, id=1, destination=Map.CELADON_MART_5F)],
    Map.CELADON_POKECENTER: [MapWarp(x=3, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=6, destination=Map.UNKNOWN)],
    Map.CERULEAN_BADGE_HOUSE: [MapWarp(x=2, y=0, id=10, destination=Map.UNKNOWN),MapWarp(x=2, y=7, id=9, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=9, destination=Map.UNKNOWN)],
    Map.CERULEAN_CAVE_1F: [MapWarp(x=24, y=17, id=7, destination=Map.UNKNOWN),MapWarp(x=25, y=17, id=7, destination=Map.UNKNOWN),MapWarp(x=27, y=1, id=1, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=23, y=7, id=2, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=18, y=9, id=3, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=7, y=1, id=4, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=1, y=3, id=5, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=3, y=11, id=6, destination=Map.CERULEAN_CAVE_2F),MapWarp(x=0, y=6, id=1, destination=Map.CERULEAN_CAVE_B1F)],
    Map.CERULEAN_CAVE_2F: [MapWarp(x=29, y=1, id=3, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=22, y=6, id=4, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=19, y=7, id=5, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=9, y=1, id=6, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=1, y=3, id=7, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=3, y=11, id=8, destination=Map.CERULEAN_CAVE_1F)],
    Map.CERULEAN_CAVE_B1F: [MapWarp(x=3, y=6, id=9, destination=Map.CERULEAN_CAVE_1F)],
    Map.CERULEAN_CITY: [MapWarp(x=27, y=11, id=1, destination=Map.CERULEAN_TRASHED_HOUSE),MapWarp(x=13, y=15, id=1, destination=Map.CERULEAN_TRADE_HOUSE),MapWarp(x=19, y=17, id=1, destination=Map.CERULEAN_POKECENTER),MapWarp(x=30, y=19, id=1, destination=Map.CERULEAN_GYM),MapWarp(x=13, y=25, id=1, destination=Map.BIKE_SHOP),MapWarp(x=25, y=25, id=1, destination=Map.CERULEAN_MART),MapWarp(x=4, y=11, id=1, destination=Map.CERULEAN_CAVE_1F),MapWarp(x=27, y=9, id=3, destination=Map.CERULEAN_TRASHED_HOUSE),MapWarp(x=9, y=11, id=2, destination=Map.CERULEAN_BADGE_HOUSE),MapWarp(x=9, y=9, id=1, destination=Map.CERULEAN_BADGE_HOUSE)],
    Map.CERULEAN_GYM: [MapWarp(x=4, y=13, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=13, id=4, destination=Map.UNKNOWN)],
    Map.CERULEAN_MART: [MapWarp(x=3, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=6, destination=Map.UNKNOWN)],
    Map.CERULEAN_POKECENTER: [MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=3, destination=Map.UNKNOWN)],
    Map.CERULEAN_TRADE_HOUSE: [MapWarp(x=2, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=2, destination=Map.UNKNOWN)],
    Map.CERULEAN_TRASHED_HOUSE: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=0, id=8, destination=Map.UNKNOWN)],
    Map.CHAMPIONS_ROOM: [MapWarp(x=3, y=7, id=2, destination=Map.LANCES_ROOM),MapWarp(x=4, y=7, id=3, destination=Map.LANCES_ROOM),MapWarp(x=3, y=0, id=1, destination=Map.HALL_OF_FAME),MapWarp(x=4, y=0, id=1, destination=Map.HALL_OF_FAME)],
    Map.CINNABAR_GYM: [MapWarp(x=16, y=17, id=2, destination=Map.UNKNOWN),MapWarp(x=17, y=17, id=2, destination=Map.UNKNOWN)],
    Map.CINNABAR_ISLAND: [MapWarp(x=6, y=3, id=2, destination=Map.POKEMON_MANSION_1F),MapWarp(x=18, y=3, id=1, destination=Map.CINNABAR_GYM),MapWarp(x=6, y=9, id=1, destination=Map.CINNABAR_LAB),MapWarp(x=11, y=11, id=1, destination=Map.CINNABAR_POKECENTER),MapWarp(x=15, y=11, id=1, destination=Map.CINNABAR_MART)],
    Map.CINNABAR_LAB: [MapWarp(x=2, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=8, y=4, id=1, destination=Map.CINNABAR_LAB_TRADE_ROOM),MapWarp(x=12, y=4, id=1, destination=Map.CINNABAR_LAB_METRONOME_ROOM),MapWarp(x=16, y=4, id=1, destination=Map.CINNABAR_LAB_FOSSIL_ROOM)],
    Map.CINNABAR_LAB_FOSSIL_ROOM: [MapWarp(x=2, y=7, id=5, destination=Map.CINNABAR_LAB),MapWarp(x=3, y=7, id=5, destination=Map.CINNABAR_LAB)],
    Map.CINNABAR_LAB_METRONOME_ROOM: [MapWarp(x=2, y=7, id=4, destination=Map.CINNABAR_LAB),MapWarp(x=3, y=7, id=4, destination=Map.CINNABAR_LAB)],
    Map.CINNABAR_LAB_TRADE_ROOM: [MapWarp(x=2, y=7, id=3, destination=Map.CINNABAR_LAB),MapWarp(x=3, y=7, id=3, destination=Map.CINNABAR_LAB)],
    Map.CINNABAR_MART: [MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN)],
    Map.CINNABAR_POKECENTER: [MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=4, destination=Map.UNKNOWN)],
    Map.COLOSSEUM: [],
    Map.COPYCATS_HOUSE_1F: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=7, y=1, id=1, destination=Map.COPYCATS_HOUSE_2F)],
    Map.COPYCATS_HOUSE_2F: [MapWarp(x=7, y=1, id=3, destination=Map.COPYCATS_HOUSE_1F)],
    Map.DAYCARE: [MapWarp(x=2, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN)],
    Map.DIGLETTS_CAVE: [MapWarp(x=5, y=5, id=3, destination=Map.DIGLETTS_CAVE_ROUTE_2),MapWarp(x=37, y=31, id=3, destination=Map.DIGLETTS_CAVE_ROUTE_11)],
    Map.DIGLETTS_CAVE_ROUTE_11: [MapWarp(x=2, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=2, destination=Map.DIGLETTS_CAVE)],
    Map.DIGLETTS_CAVE_ROUTE_2: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=1, destination=Map.DIGLETTS_CAVE)],
    Map.FIGHTING_DOJO: [MapWarp(x=4, y=11, id=2, destination=Map.UNKNOWN),MapWarp(x=5, y=11, id=2, destination=Map.UNKNOWN)],
    Map.FUCHSIA_BILLS_GRANDPAS_HOUSE: [MapWarp(x=2, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=2, destination=Map.UNKNOWN)],
    Map.FUCHSIA_CITY: [MapWarp(x=5, y=13, id=1, destination=Map.FUCHSIA_MART),MapWarp(x=11, y=27, id=1, destination=Map.FUCHSIA_BILLS_GRANDPAS_HOUSE),MapWarp(x=19, y=27, id=1, destination=Map.FUCHSIA_POKECENTER),MapWarp(x=27, y=27, id=1, destination=Map.WARDENS_HOUSE),MapWarp(x=18, y=3, id=1, destination=Map.SAFARI_ZONE_GATE),MapWarp(x=5, y=27, id=1, destination=Map.FUCHSIA_GYM),MapWarp(x=22, y=13, id=1, destination=Map.FUCHSIA_MEETING_ROOM),MapWarp(x=31, y=27, id=2, destination=Map.FUCHSIA_GOOD_ROD_HOUSE),MapWarp(x=31, y=24, id=1, destination=Map.FUCHSIA_GOOD_ROD_HOUSE)],
    Map.FUCHSIA_GOOD_ROD_HOUSE: [MapWarp(x=2, y=0, id=9, destination=Map.UNKNOWN),MapWarp(x=2, y=7, id=8, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=8, destination=Map.UNKNOWN)],
    Map.FUCHSIA_GYM: [MapWarp(x=4, y=17, id=6, destination=Map.UNKNOWN),MapWarp(x=5, y=17, id=6, destination=Map.UNKNOWN)],
    Map.FUCHSIA_MART: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.FUCHSIA_MEETING_ROOM: [MapWarp(x=4, y=7, id=7, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=7, destination=Map.UNKNOWN)],
    Map.FUCHSIA_POKECENTER: [MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=3, destination=Map.UNKNOWN)],
    Map.GAME_CORNER: [MapWarp(x=15, y=17, id=8, destination=Map.UNKNOWN),MapWarp(x=16, y=17, id=8, destination=Map.UNKNOWN),MapWarp(x=17, y=4, id=2, destination=Map.ROCKET_HIDEOUT_B1F)],
    Map.GAME_CORNER_PRIZE_ROOM: [MapWarp(x=4, y=7, id=10, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=10, destination=Map.UNKNOWN)],
    Map.HALL_OF_FAME: [MapWarp(x=4, y=7, id=3, destination=Map.CHAMPIONS_ROOM),MapWarp(x=5, y=7, id=4, destination=Map.CHAMPIONS_ROOM)],
    Map.INDIGO_PLATEAU: [MapWarp(x=9, y=5, id=1, destination=Map.INDIGO_PLATEAU_LOBBY),MapWarp(x=10, y=5, id=1, destination=Map.INDIGO_PLATEAU_LOBBY)],
    Map.INDIGO_PLATEAU_LOBBY: [MapWarp(x=7, y=11, id=1, destination=Map.UNKNOWN),MapWarp(x=8, y=11, id=2, destination=Map.UNKNOWN),MapWarp(x=8, y=0, id=1, destination=Map.LORELEIS_ROOM)],
    Map.LANCES_ROOM: [MapWarp(x=24, y=16, id=3, destination=Map.AGATHAS_ROOM),MapWarp(x=5, y=0, id=1, destination=Map.CHAMPIONS_ROOM),MapWarp(x=6, y=0, id=1, destination=Map.CHAMPIONS_ROOM)],
    Map.LAVENDER_CUBONE_HOUSE: [MapWarp(x=2, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN)],
    Map.LAVENDER_MART: [MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=4, destination=Map.UNKNOWN)],
    Map.LAVENDER_POKECENTER: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.LAVENDER_TOWN: [MapWarp(x=3, y=5, id=1, destination=Map.LAVENDER_POKECENTER),MapWarp(x=14, y=5, id=1, destination=Map.POKEMON_TOWER_1F),MapWarp(x=7, y=9, id=1, destination=Map.MR_FUJIS_HOUSE),MapWarp(x=15, y=13, id=1, destination=Map.LAVENDER_MART),MapWarp(x=3, y=13, id=1, destination=Map.LAVENDER_CUBONE_HOUSE),MapWarp(x=7, y=13, id=1, destination=Map.NAME_RATERS_HOUSE)],
    Map.LORELEIS_ROOM: [MapWarp(x=4, y=11, id=3, destination=Map.INDIGO_PLATEAU_LOBBY),MapWarp(x=5, y=11, id=3, destination=Map.INDIGO_PLATEAU_LOBBY),MapWarp(x=4, y=0, id=1, destination=Map.BRUNOS_ROOM),MapWarp(x=5, y=0, id=2, destination=Map.BRUNOS_ROOM)],
    Map.MR_FUJIS_HOUSE: [MapWarp(x=2, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN)],
    Map.MR_PSYCHICS_HOUSE: [MapWarp(x=2, y=7, id=8, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=8, destination=Map.UNKNOWN)],
    Map.MT_MOON_1F: [MapWarp(x=14, y=35, id=2, destination=Map.UNKNOWN),MapWarp(x=15, y=35, id=2, destination=Map.UNKNOWN),MapWarp(x=5, y=5, id=1, destination=Map.MT_MOON_B1F),MapWarp(x=17, y=11, id=3, destination=Map.MT_MOON_B1F),MapWarp(x=25, y=15, id=4, destination=Map.MT_MOON_B1F)],
    Map.MT_MOON_B1F: [MapWarp(x=5, y=5, id=3, destination=Map.MT_MOON_1F),MapWarp(x=17, y=11, id=1, destination=Map.MT_MOON_B2F),MapWarp(x=25, y=9, id=4, destination=Map.MT_MOON_1F),MapWarp(x=25, y=15, id=5, destination=Map.MT_MOON_1F),MapWarp(x=21, y=17, id=2, destination=Map.MT_MOON_B2F),MapWarp(x=13, y=27, id=3, destination=Map.MT_MOON_B2F),MapWarp(x=23, y=3, id=4, destination=Map.MT_MOON_B2F),MapWarp(x=27, y=3, id=3, destination=Map.UNKNOWN)],
    Map.MT_MOON_B2F: [MapWarp(x=25, y=9, id=2, destination=Map.MT_MOON_B1F),MapWarp(x=21, y=17, id=5, destination=Map.MT_MOON_B1F),MapWarp(x=15, y=27, id=6, destination=Map.MT_MOON_B1F),MapWarp(x=5, y=7, id=7, destination=Map.MT_MOON_B1F)],
    Map.MT_MOON_POKECENTER: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.MUSEUM_1F: [MapWarp(x=10, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=11, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=16, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=17, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=7, id=1, destination=Map.MUSEUM_2F)],
    Map.MUSEUM_2F: [MapWarp(x=7, y=7, id=5, destination=Map.MUSEUM_1F)],
    Map.NAME_RATERS_HOUSE: [MapWarp(x=2, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=6, destination=Map.UNKNOWN)],
    Map.OAKS_LAB: [MapWarp(x=4, y=11, id=3, destination=Map.UNKNOWN),MapWarp(x=5, y=11, id=3, destination=Map.UNKNOWN)],
    Map.PALLET_TOWN: [MapWarp(x=5, y=5, id=1, destination=Map.REDS_HOUSE_1F),MapWarp(x=13, y=5, id=1, destination=Map.BLUES_HOUSE),MapWarp(x=12, y=11, id=2, destination=Map.OAKS_LAB)],
    Map.PEWTER_CITY: [MapWarp(x=14, y=7, id=1, destination=Map.MUSEUM_1F),MapWarp(x=19, y=5, id=3, destination=Map.MUSEUM_1F),MapWarp(x=16, y=17, id=1, destination=Map.PEWTER_GYM),MapWarp(x=29, y=13, id=1, destination=Map.PEWTER_NIDORAN_HOUSE),MapWarp(x=23, y=17, id=1, destination=Map.PEWTER_MART),MapWarp(x=7, y=29, id=1, destination=Map.PEWTER_SPEECH_HOUSE),MapWarp(x=13, y=25, id=1, destination=Map.PEWTER_POKECENTER)],
    Map.PEWTER_GYM: [MapWarp(x=4, y=13, id=3, destination=Map.UNKNOWN),MapWarp(x=5, y=13, id=3, destination=Map.UNKNOWN)],
    Map.PEWTER_MART: [MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN)],
    Map.PEWTER_NIDORAN_HOUSE: [MapWarp(x=2, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN)],
    Map.PEWTER_POKECENTER: [MapWarp(x=3, y=7, id=7, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=7, destination=Map.UNKNOWN)],
    Map.PEWTER_SPEECH_HOUSE: [MapWarp(x=2, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=6, destination=Map.UNKNOWN)],
    Map.POKEMON_FAN_CLUB: [MapWarp(x=2, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=2, destination=Map.UNKNOWN)],
    Map.POKEMON_MANSION_1F: [MapWarp(x=4, y=27, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=27, id=1, destination=Map.UNKNOWN),MapWarp(x=6, y=27, id=1, destination=Map.UNKNOWN),MapWarp(x=7, y=27, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=10, id=1, destination=Map.POKEMON_MANSION_2F),MapWarp(x=21, y=23, id=1, destination=Map.POKEMON_MANSION_B1F),MapWarp(x=26, y=27, id=1, destination=Map.UNKNOWN),MapWarp(x=27, y=27, id=1, destination=Map.UNKNOWN)],
    Map.POKEMON_MANSION_2F: [MapWarp(x=5, y=10, id=5, destination=Map.POKEMON_MANSION_1F),MapWarp(x=7, y=10, id=1, destination=Map.POKEMON_MANSION_3F),MapWarp(x=25, y=14, id=3, destination=Map.POKEMON_MANSION_3F),MapWarp(x=6, y=1, id=2, destination=Map.POKEMON_MANSION_3F)],
    Map.POKEMON_MANSION_3F: [MapWarp(x=7, y=10, id=2, destination=Map.POKEMON_MANSION_2F),MapWarp(x=6, y=1, id=4, destination=Map.POKEMON_MANSION_2F),MapWarp(x=25, y=14, id=3, destination=Map.POKEMON_MANSION_2F)],
    Map.POKEMON_MANSION_B1F: [MapWarp(x=23, y=22, id=6, destination=Map.POKEMON_MANSION_1F)],
    Map.POKEMON_TOWER_1F: [MapWarp(x=10, y=17, id=2, destination=Map.UNKNOWN),MapWarp(x=11, y=17, id=2, destination=Map.UNKNOWN),MapWarp(x=18, y=9, id=2, destination=Map.POKEMON_TOWER_2F)],
    Map.POKEMON_TOWER_2F: [MapWarp(x=3, y=9, id=1, destination=Map.POKEMON_TOWER_3F),MapWarp(x=18, y=9, id=3, destination=Map.POKEMON_TOWER_1F)],
    Map.POKEMON_TOWER_3F: [MapWarp(x=3, y=9, id=1, destination=Map.POKEMON_TOWER_2F),MapWarp(x=18, y=9, id=2, destination=Map.POKEMON_TOWER_4F)],
    Map.POKEMON_TOWER_4F: [MapWarp(x=3, y=9, id=1, destination=Map.POKEMON_TOWER_5F),MapWarp(x=18, y=9, id=2, destination=Map.POKEMON_TOWER_3F)],
    Map.POKEMON_TOWER_5F: [MapWarp(x=3, y=9, id=1, destination=Map.POKEMON_TOWER_4F),MapWarp(x=18, y=9, id=1, destination=Map.POKEMON_TOWER_6F)],
    Map.POKEMON_TOWER_6F: [MapWarp(x=18, y=9, id=2, destination=Map.POKEMON_TOWER_5F),MapWarp(x=9, y=16, id=1, destination=Map.POKEMON_TOWER_7F)],
    Map.POKEMON_TOWER_7F: [MapWarp(x=9, y=16, id=2, destination=Map.POKEMON_TOWER_6F)],
    Map.POWER_PLANT: [MapWarp(x=4, y=35, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=35, id=4, destination=Map.UNKNOWN),MapWarp(x=0, y=11, id=4, destination=Map.UNKNOWN)],
    Map.REDS_HOUSE_1F: [MapWarp(x=2, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=7, y=1, id=1, destination=Map.REDS_HOUSE_2F)],
    Map.REDS_HOUSE_2F: [MapWarp(x=7, y=1, id=3, destination=Map.REDS_HOUSE_1F)],
    Map.ROCKET_HIDEOUT_B1F: [MapWarp(x=23, y=2, id=1, destination=Map.ROCKET_HIDEOUT_B2F),MapWarp(x=21, y=2, id=3, destination=Map.GAME_CORNER),MapWarp(x=24, y=19, id=1, destination=Map.ROCKET_HIDEOUT_ELEVATOR),MapWarp(x=21, y=24, id=4, destination=Map.ROCKET_HIDEOUT_B2F),MapWarp(x=25, y=19, id=2, destination=Map.ROCKET_HIDEOUT_ELEVATOR)],
    Map.ROCKET_HIDEOUT_B2F: [MapWarp(x=27, y=8, id=1, destination=Map.ROCKET_HIDEOUT_B1F),MapWarp(x=21, y=8, id=1, destination=Map.ROCKET_HIDEOUT_B3F),MapWarp(x=24, y=19, id=1, destination=Map.ROCKET_HIDEOUT_ELEVATOR),MapWarp(x=21, y=22, id=4, destination=Map.ROCKET_HIDEOUT_B1F),MapWarp(x=25, y=19, id=2, destination=Map.ROCKET_HIDEOUT_ELEVATOR)],
    Map.ROCKET_HIDEOUT_B3F: [MapWarp(x=25, y=6, id=2, destination=Map.ROCKET_HIDEOUT_B2F),MapWarp(x=19, y=18, id=1, destination=Map.ROCKET_HIDEOUT_B4F)],
    Map.ROCKET_HIDEOUT_B4F: [MapWarp(x=19, y=10, id=2, destination=Map.ROCKET_HIDEOUT_B3F),MapWarp(x=24, y=15, id=1, destination=Map.ROCKET_HIDEOUT_ELEVATOR),MapWarp(x=25, y=15, id=2, destination=Map.ROCKET_HIDEOUT_ELEVATOR)],
    Map.ROCKET_HIDEOUT_ELEVATOR: [MapWarp(x=2, y=1, id=3, destination=Map.ROCKET_HIDEOUT_B1F),MapWarp(x=3, y=1, id=5, destination=Map.ROCKET_HIDEOUT_B1F)],
    Map.ROCK_TUNNEL_1F: [MapWarp(x=15, y=3, id=2, destination=Map.UNKNOWN),MapWarp(x=15, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=15, y=33, id=3, destination=Map.UNKNOWN),MapWarp(x=15, y=35, id=3, destination=Map.UNKNOWN),MapWarp(x=37, y=3, id=1, destination=Map.ROCK_TUNNEL_B1F),MapWarp(x=5, y=3, id=2, destination=Map.ROCK_TUNNEL_B1F),MapWarp(x=17, y=11, id=3, destination=Map.ROCK_TUNNEL_B1F),MapWarp(x=37, y=17, id=4, destination=Map.ROCK_TUNNEL_B1F)],
    Map.ROCK_TUNNEL_B1F: [MapWarp(x=33, y=25, id=5, destination=Map.ROCK_TUNNEL_1F),MapWarp(x=27, y=3, id=6, destination=Map.ROCK_TUNNEL_1F),MapWarp(x=23, y=11, id=7, destination=Map.ROCK_TUNNEL_1F),MapWarp(x=3, y=3, id=8, destination=Map.ROCK_TUNNEL_1F)],
    Map.ROCK_TUNNEL_POKECENTER: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.ROUTE_1: [],
    Map.ROUTE_10: [MapWarp(x=11, y=19, id=1, destination=Map.ROCK_TUNNEL_POKECENTER),MapWarp(x=8, y=17, id=1, destination=Map.ROCK_TUNNEL_1F),MapWarp(x=8, y=53, id=3, destination=Map.ROCK_TUNNEL_1F),MapWarp(x=6, y=39, id=1, destination=Map.POWER_PLANT)],
    Map.ROUTE_11: [MapWarp(x=49, y=8, id=1, destination=Map.ROUTE_11_GATE_1F),MapWarp(x=49, y=9, id=2, destination=Map.ROUTE_11_GATE_1F),MapWarp(x=58, y=8, id=3, destination=Map.ROUTE_11_GATE_1F),MapWarp(x=58, y=9, id=4, destination=Map.ROUTE_11_GATE_1F),MapWarp(x=4, y=5, id=1, destination=Map.DIGLETTS_CAVE_ROUTE_11)],
    Map.ROUTE_11_GATE_1F: [MapWarp(x=0, y=4, id=1, destination=Map.UNKNOWN),MapWarp(x=0, y=5, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=4, id=3, destination=Map.UNKNOWN),MapWarp(x=7, y=5, id=4, destination=Map.UNKNOWN),MapWarp(x=6, y=8, id=1, destination=Map.ROUTE_11_GATE_2F)],
    Map.ROUTE_11_GATE_2F: [MapWarp(x=7, y=7, id=5, destination=Map.ROUTE_11_GATE_1F)],
    Map.ROUTE_12: [MapWarp(x=10, y=15, id=1, destination=Map.ROUTE_12_GATE_1F), MapWarp(x=11, y=15, id=2, destination=Map.ROUTE_12_GATE_1F),MapWarp(x=10, y=21, id=3, destination=Map.ROUTE_12_GATE_1F),MapWarp(x=11, y=77, id=1, destination=Map.ROUTE_12_SUPER_ROD_HOUSE)],
    Map.ROUTE_12_GATE_1F: [MapWarp(x=4, y=0, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=8, y=6, id=1, destination=Map.ROUTE_12_GATE_2F)],
    Map.ROUTE_12_GATE_2F: [MapWarp(x=7, y=7, id=5, destination=Map.ROUTE_12_GATE_1F)],
    Map.ROUTE_12_SUPER_ROD_HOUSE: [MapWarp(x=2, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN)],
    Map.ROUTE_13: [],
    Map.ROUTE_14: [],
    Map.ROUTE_15: [MapWarp(x=7, y=8, id=1, destination=Map.ROUTE_15_GATE_1F),MapWarp(x=7, y=9, id=2, destination=Map.ROUTE_15_GATE_1F),MapWarp(x=14, y=8, id=3, destination=Map.ROUTE_15_GATE_1F),MapWarp(x=14, y=9, id=4, destination=Map.ROUTE_15_GATE_1F)],
    Map.ROUTE_15_GATE_1F: [MapWarp(x=0, y=4, id=1, destination=Map.UNKNOWN),MapWarp(x=0, y=5, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=4, id=3, destination=Map.UNKNOWN),MapWarp(x=7, y=5, id=4, destination=Map.UNKNOWN),MapWarp(x=6, y=8, id=1, destination=Map.ROUTE_15_GATE_2F)],
    Map.ROUTE_15_GATE_2F: [MapWarp(x=7, y=7, id=5, destination=Map.ROUTE_15_GATE_1F)],
    Map.ROUTE_16: [MapWarp(x=17, y=10, id=1, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=17, y=11, id=2, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=24, y=10, id=3, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=24, y=11, id=4, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=17, y=4, id=5, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=17, y=5, id=6, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=24, y=4, id=7, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=24, y=5, id=8, destination=Map.ROUTE_16_GATE_1F),MapWarp(x=7, y=5, id=1, destination=Map.ROUTE_16_FLY_HOUSE)],
    Map.ROUTE_16_FLY_HOUSE: [MapWarp(x=2, y=7, id=9, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=9, destination=Map.UNKNOWN)],
    Map.ROUTE_16_GATE_1F: [MapWarp(x=0, y=8, id=1, destination=Map.UNKNOWN),MapWarp(x=0, y=9, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=8, id=3, destination=Map.UNKNOWN),MapWarp(x=7, y=9, id=3, destination=Map.UNKNOWN),MapWarp(x=0, y=2, id=5, destination=Map.UNKNOWN),MapWarp(x=0, y=3, id=6, destination=Map.UNKNOWN),MapWarp(x=7, y=2, id=7, destination=Map.UNKNOWN),MapWarp(x=7, y=3, id=8, destination=Map.UNKNOWN),MapWarp(x=6, y=12, id=1, destination=Map.ROUTE_16_GATE_2F)],
    Map.ROUTE_16_GATE_2F: [MapWarp(x=7, y=7, id=9, destination=Map.ROUTE_16_GATE_1F)],
    Map.ROUTE_17: [],
    Map.ROUTE_18: [MapWarp(x=33, y=8, id=1, destination=Map.ROUTE_18_GATE_1F),MapWarp(x=33, y=9, id=2, destination=Map.ROUTE_18_GATE_1F),MapWarp(x=40, y=8, id=3, destination=Map.ROUTE_18_GATE_1F),MapWarp(x=40, y=9, id=4, destination=Map.ROUTE_18_GATE_1F)],
    Map.ROUTE_18_GATE_1F: [MapWarp(x=0, y=4, id=1, destination=Map.UNKNOWN),MapWarp(x=0, y=5, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=4, id=3, destination=Map.UNKNOWN),MapWarp(x=7, y=5, id=4, destination=Map.UNKNOWN),MapWarp(x=6, y=8, id=1, destination=Map.ROUTE_18_GATE_2F)],
    Map.ROUTE_18_GATE_2F: [MapWarp(x=7, y=7, id=5, destination=Map.ROUTE_18_GATE_1F)],
    Map.ROUTE_19: [],
    Map.ROUTE_2: [MapWarp(x=12, y=9, id=1, destination=Map.DIGLETTS_CAVE_ROUTE_2),MapWarp(x=3, y=11, id=2, destination=Map.VIRIDIAN_FOREST_NORTH_GATE),MapWarp(x=15, y=19, id=1, destination=Map.ROUTE_2_TRADE_HOUSE),MapWarp(x=16, y=35, id=2, destination=Map.ROUTE_2_GATE),MapWarp(x=15, y=39, id=3, destination=Map.ROUTE_2_GATE),MapWarp(x=3, y=43, id=3, destination=Map.VIRIDIAN_FOREST_SOUTH_GATE)],
    Map.ROUTE_20: [MapWarp(x=48, y=5, id=1, destination=Map.SEAFOAM_ISLANDS_1F),MapWarp(x=58, y=9, id=3, destination=Map.SEAFOAM_ISLANDS_1F)],
    Map.ROUTE_21: [],
    Map.ROUTE_22: [MapWarp(x=8, y=5, id=1, destination=Map.ROUTE_22_GATE)],
    Map.ROUTE_22_GATE: [MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=0, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=0, id=2, destination=Map.UNKNOWN)],
    Map.ROUTE_23: [MapWarp(x=7, y=139, id=3, destination=Map.ROUTE_22_GATE),MapWarp(x=8, y=139, id=4, destination=Map.ROUTE_22_GATE),MapWarp(x=4, y=31, id=1, destination=Map.VICTORY_ROAD_1F),MapWarp(x=14, y=31, id=2, destination=Map.VICTORY_ROAD_2F)],
    Map.ROUTE_24: [],
    Map.ROUTE_25: [MapWarp(x=45, y=3, id=1, destination=Map.BILLS_HOUSE)],
    Map.ROUTE_2_GATE: [MapWarp(x=4, y=0, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=0, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=5, destination=Map.UNKNOWN)],
    Map.ROUTE_2_TRADE_HOUSE: [MapWarp(x=2, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN)],
    Map.ROUTE_3: [],
    Map.ROUTE_4: [MapWarp(x=11, y=5, id=1, destination=Map.MT_MOON_POKECENTER),MapWarp(x=18, y=5, id=1, destination=Map.MT_MOON_1F),MapWarp(x=24, y=5, id=8, destination=Map.MT_MOON_B1F)],
    Map.ROUTE_5: [MapWarp(x=10, y=29, id=4, destination=Map.ROUTE_5_GATE),MapWarp(x=9, y=29, id=3, destination=Map.ROUTE_5_GATE),MapWarp(x=10, y=33, id=1, destination=Map.ROUTE_5_GATE),MapWarp(x=17, y=27, id=1, destination=Map.UNDERGROUND_PATH_ROUTE_5),MapWarp(x=10, y=21, id=1, destination=Map.DAYCARE)],
    Map.ROUTE_5_GATE: [MapWarp(x=3, y=5, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=5, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=4, y=0, id=1, destination=Map.UNKNOWN)],
    Map.ROUTE_6: [MapWarp(x=9, y=1, id=3, destination=Map.ROUTE_6_GATE),MapWarp(x=10, y=1, id=3, destination=Map.ROUTE_6_GATE),MapWarp(x=10, y=7, id=1, destination=Map.ROUTE_6_GATE),MapWarp(x=17, y=13, id=1, destination=Map.UNDERGROUND_PATH_ROUTE_6)],
    Map.ROUTE_6_GATE: [MapWarp(x=3, y=5, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=5, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=4, y=0, id=2, destination=Map.UNKNOWN)],
    Map.ROUTE_7: [MapWarp(x=18, y=9, id=3, destination=Map.ROUTE_7_GATE),MapWarp(x=18, y=10, id=4, destination=Map.ROUTE_7_GATE),MapWarp(x=11, y=9, id=1, destination=Map.ROUTE_7_GATE),MapWarp(x=11, y=10, id=2, destination=Map.ROUTE_7_GATE),MapWarp(x=5, y=13, id=1, destination=Map.UNDERGROUND_PATH_ROUTE_7)],
    Map.ROUTE_7_GATE: [MapWarp(x=0, y=3, id=4, destination=Map.UNKNOWN),MapWarp(x=0, y=4, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=3, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=4, id=2, destination=Map.UNKNOWN)],
    Map.ROUTE_8: [MapWarp(x=1, y=9, id=1, destination=Map.ROUTE_8_GATE),MapWarp(x=1, y=10, id=2, destination=Map.ROUTE_8_GATE),MapWarp(x=8, y=9, id=3, destination=Map.ROUTE_8_GATE),MapWarp(x=8, y=10, id=4, destination=Map.ROUTE_8_GATE),MapWarp(x=13, y=3, id=1, destination=Map.UNDERGROUND_PATH_ROUTE_8)],
    Map.ROUTE_8_GATE: [MapWarp(x=0, y=3, id=1, destination=Map.UNKNOWN),MapWarp(x=0, y=4, id=2, destination=Map.UNKNOWN),MapWarp(x=5, y=3, id=3, destination=Map.UNKNOWN),MapWarp(x=5, y=4, id=4, destination=Map.UNKNOWN)],
    Map.ROUTE_9: [],
    Map.SAFARI_ZONE_CENTER: [MapWarp(x=14, y=25, id=3, destination=Map.SAFARI_ZONE_GATE),MapWarp(x=15, y=25, id=4, destination=Map.SAFARI_ZONE_GATE),MapWarp(x=0, y=10, id=5, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=0, y=11, id=6, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=14, y=0, id=5, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=15, y=0, id=6, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=29, y=10, id=3, destination=Map.SAFARI_ZONE_EAST),MapWarp(x=29, y=11, id=4, destination=Map.SAFARI_ZONE_EAST),MapWarp(x=17, y=19, id=1, destination=Map.SAFARI_ZONE_CENTER_REST_HOUSE)],
    Map.SAFARI_ZONE_CENTER_REST_HOUSE: [MapWarp(x=2, y=7, id=9, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=3, y=7, id=9, destination=Map.SAFARI_ZONE_CENTER)],
    Map.SAFARI_ZONE_EAST: [MapWarp(x=0, y=4, id=7, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=0, y=5, id=8, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=0, y=22, id=7, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=0, y=23, id=7, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=25, y=9, id=1, destination=Map.SAFARI_ZONE_EAST_REST_HOUSE)],
    Map.SAFARI_ZONE_EAST_REST_HOUSE: [MapWarp(x=2, y=7, id=5, destination=Map.SAFARI_ZONE_EAST),MapWarp(x=3, y=7, id=5, destination=Map.SAFARI_ZONE_EAST)],
    Map.SAFARI_ZONE_GATE: [MapWarp(x=3, y=5, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=5, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=0, id=1, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=4, y=0, id=2, destination=Map.SAFARI_ZONE_CENTER)],
    Map.SAFARI_ZONE_NORTH: [MapWarp(x=2, y=35, id=1, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=3, y=35, id=2, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=8, y=35, id=3, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=9, y=35, id=4, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=20, y=35, id=5, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=21, y=35, id=6, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=39, y=30, id=1, destination=Map.SAFARI_ZONE_EAST),MapWarp(x=39, y=31, id=2, destination=Map.SAFARI_ZONE_EAST),MapWarp(x=35, y=3, id=1, destination=Map.SAFARI_ZONE_NORTH_REST_HOUSE)],
    Map.SAFARI_ZONE_NORTH_REST_HOUSE: [MapWarp(x=2, y=7, id=9, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=3, y=7, id=9, destination=Map.SAFARI_ZONE_NORTH)],
    Map.SAFARI_ZONE_SECRET_HOUSE: [MapWarp(x=2, y=7, id=7, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=3, y=7, id=7, destination=Map.SAFARI_ZONE_WEST)],
    Map.SAFARI_ZONE_WEST: [MapWarp(x=20, y=0, id=1, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=21, y=0, id=2, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=26, y=0, id=3, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=27, y=0, id=4, destination=Map.SAFARI_ZONE_NORTH),MapWarp(x=29, y=22, id=3, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=29, y=23, id=4, destination=Map.SAFARI_ZONE_CENTER),MapWarp(x=3, y=3, id=1, destination=Map.SAFARI_ZONE_SECRET_HOUSE),MapWarp(x=11, y=11, id=1, destination=Map.SAFARI_ZONE_WEST_REST_HOUSE)],
    Map.SAFARI_ZONE_WEST_REST_HOUSE: [MapWarp(x=2, y=7, id=8, destination=Map.SAFARI_ZONE_WEST),MapWarp(x=3, y=7, id=8, destination=Map.SAFARI_ZONE_WEST)],
    Map.SAFFRON_CITY: [MapWarp(x=7, y=5, id=1, destination=Map.COPYCATS_HOUSE_1F),MapWarp(x=26, y=3, id=1, destination=Map.FIGHTING_DOJO),MapWarp(x=34, y=3, id=1, destination=Map.SAFFRON_GYM),MapWarp(x=13, y=11, id=1, destination=Map.SAFFRON_PIDGEY_HOUSE),MapWarp(x=25, y=11, id=1, destination=Map.SAFFRON_MART),MapWarp(x=18, y=21, id=1, destination=Map.SILPH_CO_1F),MapWarp(x=9, y=29, id=1, destination=Map.SAFFRON_POKECENTER),MapWarp(x=29, y=29, id=1, destination=Map.MR_PSYCHICS_HOUSE)],
    Map.SAFFRON_GYM: [MapWarp(x=8, y=17, id=3, destination=Map.UNKNOWN),MapWarp(x=9, y=17, id=3, destination=Map.UNKNOWN),MapWarp(x=1, y=3, id=23, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=3, id=16, destination=Map.SAFFRON_GYM),MapWarp(x=1, y=5, id=19, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=5, id=9, destination=Map.SAFFRON_GYM),MapWarp(x=1, y=9, id=28, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=9, id=17, destination=Map.SAFFRON_GYM),MapWarp(x=1, y=11, id=6, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=11, id=14, destination=Map.SAFFRON_GYM),MapWarp(x=1, y=15, id=24, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=15, id=31, destination=Map.SAFFRON_GYM),MapWarp(x=1, y=17, id=18, destination=Map.SAFFRON_GYM),MapWarp(x=5, y=17, id=10, destination=Map.SAFFRON_GYM),MapWarp(x=9, y=3, id=27, destination=Map.SAFFRON_GYM),MapWarp(x=11, y=3, id=4, destination=Map.SAFFRON_GYM),MapWarp(x=9, y=5, id=8, destination=Map.SAFFRON_GYM),MapWarp(x=11, y=5, id=13, destination=Map.SAFFRON_GYM),MapWarp(x=11, y=11, id=5, destination=Map.SAFFRON_GYM),MapWarp(x=11, y=15, id=32, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=3, id=25, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=3, id=29, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=5, id=3, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=5, id=11, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=9, id=21, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=9, id=30, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=11, id=15, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=11, id=7, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=15, id=22, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=15, id=26, destination=Map.SAFFRON_GYM),MapWarp(x=15, y=17, id=12, destination=Map.SAFFRON_GYM),MapWarp(x=19, y=17, id=20, destination=Map.SAFFRON_GYM)],
    Map.SAFFRON_MART: [MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN)],
    Map.SAFFRON_PIDGEY_HOUSE: [MapWarp(x=2, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN)],
    Map.SAFFRON_POKECENTER: [MapWarp(x=3, y=7, id=7, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=7, destination=Map.UNKNOWN)],
    Map.SEAFOAM_ISLANDS_1F: [MapWarp(x=4, y=17, id=1, destination=Map.UNKNOWN),MapWarp(x=5, y=17, id=1, destination=Map.UNKNOWN),MapWarp(x=26, y=17, id=2, destination=Map.UNKNOWN),MapWarp(x=27, y=17, id=2, destination=Map.UNKNOWN),MapWarp(x=7, y=5, id=2, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=25, y=3, id=7, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=23, y=15, id=5, destination=Map.SEAFOAM_ISLANDS_B1F)],
    Map.SEAFOAM_ISLANDS_B1F: [MapWarp(x=4, y=2, id=1, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=7, y=5, id=5, destination=Map.SEAFOAM_ISLANDS_1F),MapWarp(x=13, y=7, id=3, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=19, y=15, id=4, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=23, y=15, id=7, destination=Map.SEAFOAM_ISLANDS_1F),MapWarp(x=25, y=11, id=6, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=25, y=3, id=6, destination=Map.SEAFOAM_ISLANDS_1F)],
    Map.SEAFOAM_ISLANDS_B2F: [MapWarp(x=5, y=3, id=1, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=5, y=13, id=1, destination=Map.SEAFOAM_ISLANDS_B3F),MapWarp(x=13, y=7, id=3, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=19, y=15, id=4, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=25, y=3, id=4, destination=Map.SEAFOAM_ISLANDS_B3F),MapWarp(x=25, y=11, id=6, destination=Map.SEAFOAM_ISLANDS_B1F),MapWarp(x=25, y=14, id=5, destination=Map.SEAFOAM_ISLANDS_B3F)],
    Map.SEAFOAM_ISLANDS_B3F: [MapWarp(x=5, y=12, id=2, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=8, y=6, id=3, destination=Map.SEAFOAM_ISLANDS_B4F),MapWarp(x=25, y=4, id=4, destination=Map.SEAFOAM_ISLANDS_B4F),MapWarp(x=25, y=3, id=5, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=25, y=14, id=7, destination=Map.SEAFOAM_ISLANDS_B2F),MapWarp(x=20, y=17, id=1, destination=Map.SEAFOAM_ISLANDS_B4F),MapWarp(x=21, y=17, id=2, destination=Map.SEAFOAM_ISLANDS_B4F)],
    Map.SEAFOAM_ISLANDS_B4F: [MapWarp(x=20, y=17, id=6, destination=Map.SEAFOAM_ISLANDS_B3F),MapWarp(x=21, y=17, id=7, destination=Map.SEAFOAM_ISLANDS_B3F),MapWarp(x=11, y=7, id=2, destination=Map.SEAFOAM_ISLANDS_B3F),MapWarp(x=25, y=4, id=3, destination=Map.SEAFOAM_ISLANDS_B3F)],
    Map.SILPH_CO_10F: [MapWarp(x=8, y=0, id=1, destination=Map.SILPH_CO_9F),MapWarp(x=10, y=0, id=1, destination=Map.SILPH_CO_11F),MapWarp(x=12, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=9, y=11, id=4, destination=Map.SILPH_CO_4F),MapWarp(x=13, y=15, id=6, destination=Map.SILPH_CO_4F),MapWarp(x=13, y=7, id=7, destination=Map.SILPH_CO_4F)],
    Map.SILPH_CO_11F: [MapWarp(x=9, y=0, id=2, destination=Map.SILPH_CO_10F),MapWarp(x=13, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=5, y=5, id=10, destination=Map.UNKNOWN),MapWarp(x=3, y=2, id=4, destination=Map.SILPH_CO_7F)],
    Map.SILPH_CO_1F: [MapWarp(x=10, y=17, id=6, destination=Map.UNKNOWN),MapWarp(x=11, y=17, id=6, destination=Map.UNKNOWN),MapWarp(x=26, y=0, id=1, destination=Map.SILPH_CO_2F),MapWarp(x=20, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=16, y=10, id=7, destination=Map.SILPH_CO_3F)],
    Map.SILPH_CO_2F: [MapWarp(x=24, y=0, id=3, destination=Map.SILPH_CO_1F),MapWarp(x=26, y=0, id=1, destination=Map.SILPH_CO_3F),MapWarp(x=20, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=3, y=3, id=7, destination=Map.SILPH_CO_3F),MapWarp(x=13, y=3, id=5, destination=Map.SILPH_CO_8F),MapWarp(x=27, y=15, id=6, destination=Map.SILPH_CO_8F),MapWarp(x=9, y=15, id=5, destination=Map.SILPH_CO_6F)],
    Map.SILPH_CO_3F: [MapWarp(x=26, y=0, id=2, destination=Map.SILPH_CO_2F),MapWarp(x=24, y=0, id=1, destination=Map.SILPH_CO_4F),MapWarp(x=20, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=23, y=11, id=10, destination=Map.SILPH_CO_3F),MapWarp(x=3, y=3, id=6, destination=Map.SILPH_CO_5F),MapWarp(x=3, y=15, id=7, destination=Map.SILPH_CO_5F),MapWarp(x=27, y=3, id=4, destination=Map.SILPH_CO_2F),MapWarp(x=3, y=11, id=4, destination=Map.SILPH_CO_9F),MapWarp(x=11, y=11, id=5, destination=Map.SILPH_CO_7F),MapWarp(x=27, y=15, id=4, destination=Map.SILPH_CO_3F)],
    Map.SILPH_CO_4F: [MapWarp(x=24, y=0, id=2, destination=Map.SILPH_CO_3F),MapWarp(x=26, y=0, id=2, destination=Map.SILPH_CO_5F),MapWarp(x=20, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=11, y=7, id=4, destination=Map.SILPH_CO_10F),MapWarp(x=17, y=3, id=4, destination=Map.SILPH_CO_6F),MapWarp(x=3, y=15, id=5, destination=Map.SILPH_CO_10F),MapWarp(x=17, y=11, id=6, destination=Map.SILPH_CO_10F)],
    Map.SILPH_CO_5F: [MapWarp(x=24, y=0, id=2, destination=Map.SILPH_CO_6F),MapWarp(x=26, y=0, id=2, destination=Map.SILPH_CO_4F),MapWarp(x=20, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=27, y=3, id=6, destination=Map.SILPH_CO_7F),MapWarp(x=9, y=15, id=5, destination=Map.SILPH_CO_9F),MapWarp(x=11, y=5, id=5, destination=Map.SILPH_CO_3F),MapWarp(x=3, y=15, id=6, destination=Map.SILPH_CO_3F)],
    Map.SILPH_CO_6F: [MapWarp(x=16, y=0, id=2, destination=Map.SILPH_CO_7F),MapWarp(x=14, y=0, id=1, destination=Map.SILPH_CO_5F),MapWarp(x=18, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=3, y=3, id=5, destination=Map.SILPH_CO_4F),MapWarp(x=23, y=3, id=7, destination=Map.SILPH_CO_2F)],
    Map.SILPH_CO_7F: [MapWarp(x=16, y=0, id=2, destination=Map.SILPH_CO_8F),MapWarp(x=22, y=0, id=1, destination=Map.SILPH_CO_6F),MapWarp(x=18, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=5, y=7, id=4, destination=Map.SILPH_CO_11F),MapWarp(x=5, y=3, id=9, destination=Map.SILPH_CO_3F),MapWarp(x=21, y=15, id=4, destination=Map.SILPH_CO_5F)],
    Map.SILPH_CO_8F: [MapWarp(x=16, y=0, id=2, destination=Map.SILPH_CO_9F),MapWarp(x=14, y=0, id=1, destination=Map.SILPH_CO_7F),MapWarp(x=18, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=3, y=11, id=7, destination=Map.SILPH_CO_8F),MapWarp(x=3, y=15, id=5, destination=Map.SILPH_CO_2F),MapWarp(x=11, y=5, id=6, destination=Map.SILPH_CO_2F),MapWarp(x=11, y=9, id=4, destination=Map.SILPH_CO_8F)],
    Map.SILPH_CO_9F: [MapWarp(x=14, y=0, id=1, destination=Map.SILPH_CO_10F),MapWarp(x=16, y=0, id=1, destination=Map.SILPH_CO_8F),MapWarp(x=18, y=0, id=1, destination=Map.SILPH_CO_ELEVATOR),MapWarp(x=9, y=3, id=8, destination=Map.SILPH_CO_3F),MapWarp(x=17, y=15, id=5, destination=Map.SILPH_CO_5F)],
    Map.SILPH_CO_ELEVATOR: [MapWarp(x=1, y=3, id=1, destination=Map.UNUSED_MAP_ED),MapWarp(x=2, y=3, id=1, destination=Map.UNUSED_MAP_ED)],
    Map.SS_ANNE_1F: [MapWarp(x=26, y=0, id=2, destination=Map.VERMILION_DOCK),MapWarp(x=27, y=0, id=2, destination=Map.VERMILION_DOCK),MapWarp(x=31, y=8, id=1, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=23, y=8, id=2, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=19, y=8, id=3, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=15, y=8, id=4, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=11, y=8, id=5, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=7, y=8, id=6, destination=Map.SS_ANNE_1F_ROOMS),MapWarp(x=2, y=6, id=7, destination=Map.SS_ANNE_2F),MapWarp(x=37, y=15, id=6, destination=Map.SS_ANNE_B1F),MapWarp(x=3, y=16, id=1, destination=Map.SS_ANNE_KITCHEN)],
    Map.SS_ANNE_1F_ROOMS: [MapWarp(x=0, y=0, id=3, destination=Map.SS_ANNE_1F),MapWarp(x=10, y=0, id=4, destination=Map.SS_ANNE_1F),MapWarp(x=20, y=0, id=5, destination=Map.SS_ANNE_1F),MapWarp(x=0, y=10, id=6, destination=Map.SS_ANNE_1F),MapWarp(x=10, y=10, id=7, destination=Map.SS_ANNE_1F),MapWarp(x=20, y=10, id=8, destination=Map.SS_ANNE_1F)],
    Map.SS_ANNE_2F: [MapWarp(x=9, y=11, id=1, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=13, y=11, id=3, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=17, y=11, id=5, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=21, y=11, id=7, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=25, y=11, id=9, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=29, y=11, id=11, destination=Map.SS_ANNE_2F_ROOMS),MapWarp(x=2, y=4, id=9, destination=Map.SS_ANNE_1F),MapWarp(x=2, y=12, id=2, destination=Map.SS_ANNE_3F),MapWarp(x=36, y=4, id=1, destination=Map.SS_ANNE_CAPTAINS_ROOM)],
    Map.SS_ANNE_2F_ROOMS: [MapWarp(x=2, y=5, id=1, destination=Map.SS_ANNE_2F),MapWarp(x=3, y=5, id=1, destination=Map.SS_ANNE_2F),MapWarp(x=12, y=5, id=2, destination=Map.SS_ANNE_2F),MapWarp(x=13, y=5, id=2, destination=Map.SS_ANNE_2F),MapWarp(x=22, y=5, id=3, destination=Map.SS_ANNE_2F),MapWarp(x=23, y=5, id=3, destination=Map.SS_ANNE_2F),MapWarp(x=2, y=15, id=4, destination=Map.SS_ANNE_2F),MapWarp(x=3, y=15, id=4, destination=Map.SS_ANNE_2F),MapWarp(x=12, y=15, id=5, destination=Map.SS_ANNE_2F),MapWarp(x=13, y=15, id=5, destination=Map.SS_ANNE_2F),MapWarp(x=22, y=15, id=6, destination=Map.SS_ANNE_2F),MapWarp(x=23, y=15, id=6, destination=Map.SS_ANNE_2F)],
    Map.SS_ANNE_3F: [MapWarp(x=0, y=3, id=1, destination=Map.SS_ANNE_BOW),MapWarp(x=19, y=3, id=8, destination=Map.SS_ANNE_2F)],
    Map.SS_ANNE_B1F: [MapWarp(x=23, y=3, id=9, destination=Map.SS_ANNE_B1F_ROOMS),MapWarp(x=19, y=3, id=7, destination=Map.SS_ANNE_B1F_ROOMS),MapWarp(x=15, y=3, id=5, destination=Map.SS_ANNE_B1F_ROOMS),MapWarp(x=11, y=3, id=3, destination=Map.SS_ANNE_B1F_ROOMS),MapWarp(x=7, y=3, id=1, destination=Map.SS_ANNE_B1F_ROOMS),MapWarp(x=27, y=5, id=10, destination=Map.SS_ANNE_1F)],
    Map.SS_ANNE_B1F_ROOMS: [MapWarp(x=2, y=5, id=5, destination=Map.SS_ANNE_B1F),MapWarp(x=3, y=5, id=5, destination=Map.SS_ANNE_B1F),MapWarp(x=12, y=5, id=4, destination=Map.SS_ANNE_B1F),MapWarp(x=13, y=5, id=4, destination=Map.SS_ANNE_B1F),MapWarp(x=22, y=5, id=3, destination=Map.SS_ANNE_B1F),MapWarp(x=23, y=5, id=3, destination=Map.SS_ANNE_B1F),MapWarp(x=2, y=15, id=2, destination=Map.SS_ANNE_B1F),MapWarp(x=3, y=15, id=2, destination=Map.SS_ANNE_B1F),MapWarp(x=12, y=15, id=1, destination=Map.SS_ANNE_B1F),MapWarp(x=13, y=15, id=1, destination=Map.SS_ANNE_B1F)],
    Map.SS_ANNE_BOW: [MapWarp(x=13, y=6, id=1, destination=Map.SS_ANNE_3F),MapWarp(x=13, y=7, id=1, destination=Map.SS_ANNE_3F)],
    Map.SS_ANNE_CAPTAINS_ROOM: [MapWarp(x=0, y=7, id=9, destination=Map.SS_ANNE_2F)],
    Map.SS_ANNE_KITCHEN: [MapWarp(x=6, y=0, id=11, destination=Map.SS_ANNE_1F)],
    Map.TRADE_CENTER: [],
    Map.UNDERGROUND_PATH_NORTH_SOUTH: [MapWarp(x=5, y=4, id=3, destination=Map.UNDERGROUND_PATH_ROUTE_5),MapWarp(x=2, y=41, id=3, destination=Map.UNDERGROUND_PATH_ROUTE_6)],
    Map.UNDERGROUND_PATH_ROUTE_5: [MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=1, destination=Map.UNDERGROUND_PATH_NORTH_SOUTH)],
    Map.UNDERGROUND_PATH_ROUTE_6: [MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=2, destination=Map.UNDERGROUND_PATH_NORTH_SOUTH)],
    Map.UNDERGROUND_PATH_ROUTE_7: [MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=1, destination=Map.UNDERGROUND_PATH_WEST_EAST)],
    Map.UNDERGROUND_PATH_ROUTE_7_COPY: [MapWarp(x=3, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=1, destination=Map.UNDERGROUND_PATH_WEST_EAST)],
    Map.UNDERGROUND_PATH_ROUTE_8: [MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=4, y=4, id=2, destination=Map.UNDERGROUND_PATH_WEST_EAST)],
    Map.UNDERGROUND_PATH_WEST_EAST: [MapWarp(x=2, y=5, id=3, destination=Map.UNDERGROUND_PATH_ROUTE_7),MapWarp(x=47, y=2, id=3, destination=Map.UNDERGROUND_PATH_ROUTE_8)],
    Map.VERMILION_CITY: [MapWarp(x=11, y=3, id=1, destination=Map.VERMILION_POKECENTER),MapWarp(x=9, y=13, id=1, destination=Map.POKEMON_FAN_CLUB),MapWarp(x=23, y=13, id=1, destination=Map.VERMILION_MART),MapWarp(x=12, y=19, id=1, destination=Map.VERMILION_GYM),MapWarp(x=23, y=19, id=1, destination=Map.VERMILION_PIDGEY_HOUSE),MapWarp(x=18, y=31, id=1, destination=Map.VERMILION_DOCK),MapWarp(x=19, y=31, id=1, destination=Map.VERMILION_DOCK),MapWarp(x=15, y=13, id=1, destination=Map.VERMILION_TRADE_HOUSE),MapWarp(x=7, y=3, id=1, destination=Map.VERMILION_OLD_ROD_HOUSE)],
    Map.VERMILION_DOCK: [MapWarp(x=14, y=0, id=6, destination=Map.UNKNOWN),MapWarp(x=14, y=2, id=2, destination=Map.SS_ANNE_1F)],
    Map.VERMILION_GYM: [MapWarp(x=4, y=17, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=17, id=4, destination=Map.UNKNOWN)],
    Map.VERMILION_MART: [MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=3, destination=Map.UNKNOWN)],
    Map.VERMILION_OLD_ROD_HOUSE: [MapWarp(x=2, y=7, id=9, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=9, destination=Map.UNKNOWN)],
    Map.VERMILION_PIDGEY_HOUSE: [MapWarp(x=2, y=7, id=5, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=5, destination=Map.UNKNOWN)],
    Map.VERMILION_POKECENTER: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.VERMILION_TRADE_HOUSE: [MapWarp(x=2, y=7, id=8, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=8, destination=Map.UNKNOWN)],
    Map.VICTORY_ROAD_1F: [MapWarp(x=8, y=17, id=3, destination=Map.UNKNOWN),MapWarp(x=9, y=17, id=3, destination=Map.UNKNOWN),MapWarp(x=1, y=1, id=1, destination=Map.VICTORY_ROAD_2F)],
    Map.VICTORY_ROAD_2F: [MapWarp(x=0, y=8, id=3, destination=Map.VICTORY_ROAD_1F),MapWarp(x=29, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=29, y=8, id=4, destination=Map.UNKNOWN),MapWarp(x=23, y=7, id=1, destination=Map.VICTORY_ROAD_3F),MapWarp(x=25, y=14, id=3, destination=Map.VICTORY_ROAD_3F),MapWarp(x=27, y=7, id=2, destination=Map.VICTORY_ROAD_3F),MapWarp(x=1, y=1, id=4, destination=Map.VICTORY_ROAD_3F)],
    Map.VICTORY_ROAD_3F: [MapWarp(x=23, y=7, id=4, destination=Map.VICTORY_ROAD_2F),MapWarp(x=26, y=8, id=6, destination=Map.VICTORY_ROAD_2F),MapWarp(x=27, y=15, id=5, destination=Map.VICTORY_ROAD_2F),MapWarp(x=2, y=0, id=7, destination=Map.VICTORY_ROAD_2F)],
    Map.VIRIDIAN_CITY: [MapWarp(x=23, y=25, id=1, destination=Map.VIRIDIAN_POKECENTER),MapWarp(x=29, y=19, id=1, destination=Map.VIRIDIAN_MART),MapWarp(x=21, y=15, id=1, destination=Map.VIRIDIAN_SCHOOL_HOUSE),MapWarp(x=21, y=9, id=1, destination=Map.VIRIDIAN_NICKNAME_HOUSE),MapWarp(x=32, y=7, id=1, destination=Map.VIRIDIAN_GYM)],
    Map.VIRIDIAN_FOREST: [MapWarp(x=1, y=0, id=3, destination=Map.VIRIDIAN_FOREST_NORTH_GATE),MapWarp(x=2, y=0, id=4, destination=Map.VIRIDIAN_FOREST_NORTH_GATE),MapWarp(x=15, y=47, id=2, destination=Map.VIRIDIAN_FOREST_SOUTH_GATE),MapWarp(x=16, y=47, id=2, destination=Map.VIRIDIAN_FOREST_SOUTH_GATE),MapWarp(x=17, y=47, id=2, destination=Map.VIRIDIAN_FOREST_SOUTH_GATE),MapWarp(x=18, y=47, id=2, destination=Map.VIRIDIAN_FOREST_SOUTH_GATE)],
    Map.VIRIDIAN_FOREST_NORTH_GATE: [MapWarp(x=4, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=5, y=0, id=2, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.VIRIDIAN_FOREST),MapWarp(x=5, y=7, id=1, destination=Map.VIRIDIAN_FOREST)],
    Map.VIRIDIAN_FOREST_SOUTH_GATE: [MapWarp(x=4, y=0, id=4, destination=Map.VIRIDIAN_FOREST),MapWarp(x=5, y=0, id=5, destination=Map.VIRIDIAN_FOREST),MapWarp(x=4, y=7, id=6, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=6, destination=Map.UNKNOWN)],
    Map.VIRIDIAN_GYM: [MapWarp(x=16, y=17, id=5, destination=Map.UNKNOWN),MapWarp(x=17, y=17, id=5, destination=Map.UNKNOWN)],
    Map.VIRIDIAN_MART: [MapWarp(x=3, y=7, id=2, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=2, destination=Map.UNKNOWN)],
    Map.VIRIDIAN_NICKNAME_HOUSE: [MapWarp(x=2, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=4, destination=Map.UNKNOWN)],
    Map.VIRIDIAN_POKECENTER: [MapWarp(x=3, y=7, id=1, destination=Map.UNKNOWN),MapWarp(x=4, y=7, id=1, destination=Map.UNKNOWN)],
    Map.VIRIDIAN_SCHOOL_HOUSE: [MapWarp(x=2, y=7, id=3, destination=Map.UNKNOWN),MapWarp(x=3, y=7, id=3, destination=Map.UNKNOWN)],
    Map.WARDENS_HOUSE: [MapWarp(x=4, y=7, id=4, destination=Map.UNKNOWN),MapWarp(x=5, y=7, id=4, destination=Map.UNKNOWN)],
}

# We use different ids for named warps, as sometimes, the game uses the latest map visited in memory to choose where to warp.
# We need to include in the name the destination
NamedWarpIds = {
    f"{warp.destination.name}@{warp.id}": warp.global_id
    for warplist in MapWarps.values()
    for warp in warplist
}