from typing import NamedTuple
from deepred.polaris_env.pokemon_red.enums import Map


class MapDimension(NamedTuple):
    width: int = 50
    height: int = 50


    @property
    def shape(self):
        """
        The shape of the map (width, height).
        """
        return self.width, self.height


MapDimensions = {
    Map.PALLET_TOWN: MapDimension(width=20, height=18),
    Map.VIRIDIAN_CITY: MapDimension(width=40, height=36),
    Map.PEWTER_CITY: MapDimension(width=40, height=36),
    Map.CERULEAN_CITY: MapDimension(width=40, height=36),
    Map.LAVENDER_TOWN: MapDimension(width=20, height=18),
    Map.VERMILION_CITY: MapDimension(width=40, height=36),
    Map.CELADON_CITY: MapDimension(width=50, height=36),
    Map.FUCHSIA_CITY: MapDimension(width=40, height=36),
    Map.CINNABAR_ISLAND: MapDimension(width=20, height=18),
    Map.INDIGO_PLATEAU: MapDimension(width=20, height=18),
    Map.SAFFRON_CITY: MapDimension(width=40, height=36),
    Map.UNUSED_MAP_0B: MapDimension(),
    Map.ROUTE_1: MapDimension(width=20, height=36),
    Map.ROUTE_2: MapDimension(width=20, height=72),
    Map.ROUTE_3: MapDimension(width=70, height=18),
    Map.ROUTE_4: MapDimension(width=90, height=18),
    Map.ROUTE_5: MapDimension(width=20, height=36),
    Map.ROUTE_6: MapDimension(width=20, height=36),
    Map.ROUTE_7: MapDimension(width=20, height=18),
    Map.ROUTE_8: MapDimension(width=60, height=18),
    Map.ROUTE_9: MapDimension(width=60, height=18),
    Map.ROUTE_10: MapDimension(width=20, height=72),
    Map.ROUTE_11: MapDimension(width=60, height=18),
    Map.ROUTE_12: MapDimension(width=20, height=108),
    Map.ROUTE_13: MapDimension(width=60, height=18),
    Map.ROUTE_14: MapDimension(width=20, height=54),
    Map.ROUTE_15: MapDimension(width=60, height=18),
    Map.ROUTE_16: MapDimension(width=40, height=18),
    Map.ROUTE_17: MapDimension(width=20, height=144),
    Map.ROUTE_18: MapDimension(width=50, height=18),
    Map.ROUTE_19: MapDimension(width=20, height=54),
    Map.ROUTE_20: MapDimension(width=100, height=18),
    Map.ROUTE_21: MapDimension(width=20, height=90),
    Map.ROUTE_22: MapDimension(width=40, height=18),
    Map.ROUTE_23: MapDimension(width=20, height=144),
    Map.ROUTE_24: MapDimension(width=20, height=36),
    Map.ROUTE_25: MapDimension(width=60, height=18),
    Map.REDS_HOUSE_1F: MapDimension(width=8, height=8),
    Map.REDS_HOUSE_2F: MapDimension(width=8, height=8),
    Map.BLUES_HOUSE: MapDimension(width=8, height=8),
    Map.OAKS_LAB: MapDimension(width=10, height=12),
    Map.VIRIDIAN_POKECENTER: MapDimension(width=14, height=8),
    Map.VIRIDIAN_MART: MapDimension(width=8, height=8),
    Map.VIRIDIAN_SCHOOL_HOUSE: MapDimension(width=8, height=8),
    Map.VIRIDIAN_NICKNAME_HOUSE: MapDimension(width=8, height=8),
    Map.VIRIDIAN_GYM: MapDimension(width=20, height=18),
    Map.DIGLETTS_CAVE_ROUTE_2: MapDimension(width=8, height=8),
    Map.VIRIDIAN_FOREST_NORTH_GATE: MapDimension(width=10, height=8),
    Map.ROUTE_2_TRADE_HOUSE: MapDimension(width=8, height=8),
    Map.ROUTE_2_GATE: MapDimension(width=10, height=8),
    Map.VIRIDIAN_FOREST_SOUTH_GATE: MapDimension(width=10, height=8),
    Map.VIRIDIAN_FOREST: MapDimension(width=34, height=48),
    Map.MUSEUM_1F: MapDimension(width=20, height=8),
    Map.MUSEUM_2F: MapDimension(width=14, height=8),
    Map.PEWTER_GYM: MapDimension(width=10, height=14),
    Map.PEWTER_NIDORAN_HOUSE: MapDimension(width=8, height=8),
    Map.PEWTER_MART: MapDimension(width=8, height=8),
    Map.PEWTER_SPEECH_HOUSE: MapDimension(width=8, height=8),
    Map.PEWTER_POKECENTER: MapDimension(width=14, height=8),
    Map.MT_MOON_1F: MapDimension(width=40, height=36),
    Map.MT_MOON_B1F: MapDimension(width=28, height=28),
    Map.MT_MOON_B2F: MapDimension(width=40, height=36),
    Map.CERULEAN_TRASHED_HOUSE: MapDimension(width=8, height=8),
    Map.CERULEAN_TRADE_HOUSE: MapDimension(width=8, height=8),
    Map.CERULEAN_POKECENTER: MapDimension(width=14, height=8),
    Map.CERULEAN_GYM: MapDimension(width=10, height=14),
    Map.BIKE_SHOP: MapDimension(width=8, height=8),
    Map.CERULEAN_MART: MapDimension(width=8, height=8),
    Map.MT_MOON_POKECENTER: MapDimension(width=14, height=8),
    Map.CERULEAN_TRASHED_HOUSE_COPY: MapDimension(width=8, height=8),
    Map.ROUTE_5_GATE: MapDimension(width=8, height=6),
    Map.UNDERGROUND_PATH_ROUTE_5: MapDimension(width=8, height=8),
    Map.DAYCARE: MapDimension(width=8, height=8),
    Map.ROUTE_6_GATE: MapDimension(width=8, height=6),
    Map.UNDERGROUND_PATH_ROUTE_6: MapDimension(width=8, height=8),
    Map.UNDERGROUND_PATH_ROUTE_6_COPY: MapDimension(width=8, height=8),
    Map.ROUTE_7_GATE: MapDimension(width=6, height=8),
    Map.UNDERGROUND_PATH_ROUTE_7: MapDimension(width=8, height=8),
    Map.UNDERGROUND_PATH_ROUTE_7_COPY: MapDimension(width=8, height=8),
    Map.ROUTE_8_GATE: MapDimension(width=6, height=8),
    Map.UNDERGROUND_PATH_ROUTE_8: MapDimension(width=8, height=8),
    Map.ROCK_TUNNEL_POKECENTER: MapDimension(width=14, height=8),
    Map.ROCK_TUNNEL_1F: MapDimension(width=40, height=36),
    Map.POWER_PLANT: MapDimension(width=40, height=36),
    Map.ROUTE_11_GATE_1F: MapDimension(width=8, height=10),
    Map.DIGLETTS_CAVE_ROUTE_11: MapDimension(width=8, height=8),
    Map.ROUTE_11_GATE_2F: MapDimension(width=8, height=8),
    Map.ROUTE_12_GATE_1F: MapDimension(width=10, height=8),
    Map.BILLS_HOUSE: MapDimension(width=8, height=8),
    Map.VERMILION_POKECENTER: MapDimension(width=14, height=8),
    Map.POKEMON_FAN_CLUB: MapDimension(width=8, height=8),
    Map.VERMILION_MART: MapDimension(width=8, height=8),
    Map.VERMILION_GYM: MapDimension(width=10, height=18),
    Map.VERMILION_PIDGEY_HOUSE: MapDimension(width=8, height=8),
    Map.VERMILION_DOCK: MapDimension(width=28, height=12),
    Map.SS_ANNE_1F: MapDimension(width=40, height=18),
    Map.SS_ANNE_2F: MapDimension(width=40, height=18),
    Map.SS_ANNE_3F: MapDimension(width=20, height=6),
    Map.SS_ANNE_B1F: MapDimension(width=30, height=8),
    Map.SS_ANNE_BOW: MapDimension(width=20, height=14),
    Map.SS_ANNE_KITCHEN: MapDimension(width=14, height=16),
    Map.SS_ANNE_CAPTAINS_ROOM: MapDimension(width=6, height=8),
    Map.SS_ANNE_1F_ROOMS: MapDimension(width=24, height=16),
    Map.SS_ANNE_2F_ROOMS: MapDimension(width=24, height=16),
    Map.SS_ANNE_B1F_ROOMS: MapDimension(width=24, height=16),
    Map.UNUSED_MAP_69: MapDimension(),
    Map.UNUSED_MAP_6A: MapDimension(),
    Map.UNUSED_MAP_6B: MapDimension(),
    Map.VICTORY_ROAD_1F: MapDimension(width=20, height=18),
    Map.UNUSED_MAP_6D: MapDimension(),
    Map.UNUSED_MAP_6E: MapDimension(),
    Map.UNUSED_MAP_6F: MapDimension(),
    Map.UNUSED_MAP_70: MapDimension(),
    Map.LANCES_ROOM: MapDimension(width=26, height=26),
    Map.UNUSED_MAP_72: MapDimension(),
    Map.UNUSED_MAP_73: MapDimension(),
    Map.UNUSED_MAP_74: MapDimension(),
    Map.UNUSED_MAP_75: MapDimension(),
    Map.HALL_OF_FAME: MapDimension(width=10, height=8),
    Map.UNDERGROUND_PATH_NORTH_SOUTH: MapDimension(width=8, height=48),
    Map.CHAMPIONS_ROOM: MapDimension(width=8, height=8),
    Map.UNDERGROUND_PATH_WEST_EAST: MapDimension(width=50, height=8),
    Map.CELADON_MART_1F: MapDimension(width=20, height=8),
    Map.CELADON_MART_2F: MapDimension(width=20, height=8),
    Map.CELADON_MART_3F: MapDimension(width=20, height=8),
    Map.CELADON_MART_4F: MapDimension(width=20, height=8),
    Map.CELADON_MART_ROOF: MapDimension(width=20, height=8),
    Map.CELADON_MART_ELEVATOR: MapDimension(width=4, height=4),
    Map.CELADON_MANSION_1F: MapDimension(width=8, height=12),
    Map.CELADON_MANSION_2F: MapDimension(width=8, height=12),
    Map.CELADON_MANSION_3F: MapDimension(width=8, height=12),
    Map.CELADON_MANSION_ROOF: MapDimension(width=8, height=12),
    Map.CELADON_MANSION_ROOF_HOUSE: MapDimension(width=8, height=8),
    Map.CELADON_POKECENTER: MapDimension(width=14, height=8),
    Map.CELADON_GYM: MapDimension(width=10, height=18),
    Map.GAME_CORNER: MapDimension(width=20, height=18),
    Map.CELADON_MART_5F: MapDimension(width=20, height=8),
    Map.GAME_CORNER_PRIZE_ROOM: MapDimension(width=10, height=8),
    Map.CELADON_DINER: MapDimension(width=10, height=8),
    Map.CELADON_CHIEF_HOUSE: MapDimension(width=8, height=8),
    Map.CELADON_HOTEL: MapDimension(width=14, height=8),
    Map.LAVENDER_POKECENTER: MapDimension(width=14, height=8),
    Map.POKEMON_TOWER_1F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_2F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_3F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_4F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_5F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_6F: MapDimension(width=20, height=18),
    Map.POKEMON_TOWER_7F: MapDimension(width=20, height=18),
    Map.MR_FUJIS_HOUSE: MapDimension(width=8, height=8),
    Map.LAVENDER_MART: MapDimension(width=8, height=8),
    Map.LAVENDER_CUBONE_HOUSE: MapDimension(width=8, height=8),
    Map.FUCHSIA_MART: MapDimension(width=8, height=8),
    Map.FUCHSIA_BILLS_GRANDPAS_HOUSE: MapDimension(width=8, height=8),
    Map.FUCHSIA_POKECENTER: MapDimension(width=14, height=8),
    Map.WARDENS_HOUSE: MapDimension(width=10, height=8),
    Map.SAFARI_ZONE_GATE: MapDimension(width=8, height=6),
    Map.FUCHSIA_GYM: MapDimension(width=10, height=18),
    Map.FUCHSIA_MEETING_ROOM: MapDimension(width=14, height=8),
    Map.SEAFOAM_ISLANDS_B1F: MapDimension(width=30, height=18),
    Map.SEAFOAM_ISLANDS_B2F: MapDimension(width=30, height=18),
    Map.SEAFOAM_ISLANDS_B3F: MapDimension(width=30, height=18),
    Map.SEAFOAM_ISLANDS_B4F: MapDimension(width=30, height=18),
    Map.VERMILION_OLD_ROD_HOUSE: MapDimension(width=8, height=8),
    Map.FUCHSIA_GOOD_ROD_HOUSE: MapDimension(width=8, height=8),
    Map.POKEMON_MANSION_1F: MapDimension(width=30, height=28),
    Map.CINNABAR_GYM: MapDimension(width=20, height=18),
    Map.CINNABAR_LAB: MapDimension(width=18, height=8),
    Map.CINNABAR_LAB_TRADE_ROOM: MapDimension(width=8, height=8),
    Map.CINNABAR_LAB_METRONOME_ROOM: MapDimension(width=8, height=8),
    Map.CINNABAR_LAB_FOSSIL_ROOM: MapDimension(width=8, height=8),
    Map.CINNABAR_POKECENTER: MapDimension(width=14, height=8),
    Map.CINNABAR_MART: MapDimension(width=8, height=8),
    Map.CINNABAR_MART_COPY: MapDimension(width=8, height=8),
    Map.INDIGO_PLATEAU_LOBBY: MapDimension(width=16, height=12),
    Map.COPYCATS_HOUSE_1F: MapDimension(width=8, height=8),
    Map.COPYCATS_HOUSE_2F: MapDimension(width=8, height=8),
    Map.FIGHTING_DOJO: MapDimension(width=10, height=12),
    Map.SAFFRON_GYM: MapDimension(width=20, height=18),
    Map.SAFFRON_PIDGEY_HOUSE: MapDimension(width=8, height=8),
    Map.SAFFRON_MART: MapDimension(width=8, height=8),
    Map.SILPH_CO_1F: MapDimension(width=30, height=18),
    Map.SAFFRON_POKECENTER: MapDimension(width=14, height=8),
    Map.MR_PSYCHICS_HOUSE: MapDimension(width=8, height=8),
    Map.ROUTE_15_GATE_1F: MapDimension(width=8, height=10),
    Map.ROUTE_15_GATE_2F: MapDimension(width=8, height=8),
    Map.ROUTE_16_GATE_1F: MapDimension(width=8, height=14),
    Map.ROUTE_16_GATE_2F: MapDimension(width=8, height=8),
    Map.ROUTE_16_FLY_HOUSE: MapDimension(width=8, height=8),
    Map.ROUTE_12_SUPER_ROD_HOUSE: MapDimension(width=8, height=8),
    Map.ROUTE_18_GATE_1F: MapDimension(width=8, height=10),
    Map.ROUTE_18_GATE_2F: MapDimension(width=8, height=8),
    Map.SEAFOAM_ISLANDS_1F: MapDimension(width=30, height=18),
    Map.ROUTE_22_GATE: MapDimension(width=10, height=8),
    Map.VICTORY_ROAD_2F: MapDimension(width=30, height=18),
    Map.ROUTE_12_GATE_2F: MapDimension(width=8, height=8),
    Map.VERMILION_TRADE_HOUSE: MapDimension(width=8, height=8),
    Map.DIGLETTS_CAVE: MapDimension(width=40, height=36),
    Map.VICTORY_ROAD_3F: MapDimension(width=30, height=18),
    Map.ROCKET_HIDEOUT_B1F: MapDimension(width=30, height=28),
    Map.ROCKET_HIDEOUT_B2F: MapDimension(width=30, height=28),
    Map.ROCKET_HIDEOUT_B3F: MapDimension(width=30, height=28),
    Map.ROCKET_HIDEOUT_B4F: MapDimension(width=30, height=24),
    Map.ROCKET_HIDEOUT_ELEVATOR: MapDimension(width=6, height=8),
    Map.UNUSED_MAP_CC: MapDimension(),
    Map.UNUSED_MAP_CD: MapDimension(),
    Map.UNUSED_MAP_CE: MapDimension(),
    Map.SILPH_CO_2F: MapDimension(width=30, height=18),
    Map.SILPH_CO_3F: MapDimension(width=30, height=18),
    Map.SILPH_CO_4F: MapDimension(width=30, height=18),
    Map.SILPH_CO_5F: MapDimension(width=30, height=18),
    Map.SILPH_CO_6F: MapDimension(width=26, height=18),
    Map.SILPH_CO_7F: MapDimension(width=26, height=18),
    Map.SILPH_CO_8F: MapDimension(width=26, height=18),
    Map.POKEMON_MANSION_2F: MapDimension(width=30, height=28),
    Map.POKEMON_MANSION_3F: MapDimension(width=30, height=18),
    Map.POKEMON_MANSION_B1F: MapDimension(width=30, height=28),
    Map.SAFARI_ZONE_EAST: MapDimension(width=30, height=26),
    Map.SAFARI_ZONE_NORTH: MapDimension(width=40, height=36),
    Map.SAFARI_ZONE_WEST: MapDimension(width=30, height=26),
    Map.SAFARI_ZONE_CENTER: MapDimension(width=30, height=26),
    Map.SAFARI_ZONE_CENTER_REST_HOUSE: MapDimension(width=8, height=8),
    Map.SAFARI_ZONE_SECRET_HOUSE: MapDimension(width=8, height=8),
    Map.SAFARI_ZONE_WEST_REST_HOUSE: MapDimension(width=8, height=8),
    Map.SAFARI_ZONE_EAST_REST_HOUSE: MapDimension(width=8, height=8),
    Map.SAFARI_ZONE_NORTH_REST_HOUSE: MapDimension(width=8, height=8),
    Map.CERULEAN_CAVE_2F: MapDimension(width=30, height=18),
    Map.CERULEAN_CAVE_B1F: MapDimension(width=30, height=18),
    Map.CERULEAN_CAVE_1F: MapDimension(width=30, height=18),
    Map.NAME_RATERS_HOUSE: MapDimension(width=8, height=8),
    Map.CERULEAN_BADGE_HOUSE: MapDimension(width=8, height=8),
    Map.UNUSED_MAP_E7: MapDimension(),
    Map.ROCK_TUNNEL_B1F: MapDimension(width=40, height=36),
    Map.SILPH_CO_9F: MapDimension(width=26, height=18),
    Map.SILPH_CO_10F: MapDimension(width=16, height=18),
    Map.SILPH_CO_11F: MapDimension(width=18, height=18),
    Map.SILPH_CO_ELEVATOR: MapDimension(width=4, height=4),
    Map.UNUSED_MAP_ED: MapDimension(),
    Map.UNUSED_MAP_EE: MapDimension(),
    Map.TRADE_CENTER: MapDimension(width=10, height=8),
    Map.COLOSSEUM: MapDimension(width=10, height=8),
    Map.UNUSED_MAP_F1: MapDimension(),
    Map.UNUSED_MAP_F2: MapDimension(),
    Map.UNUSED_MAP_F3: MapDimension(),
    Map.UNUSED_MAP_F4: MapDimension(),
    Map.LORELEIS_ROOM: MapDimension(width=10, height=12),
    Map.BRUNOS_ROOM: MapDimension(width=10, height=12),
    Map.AGATHAS_ROOM: MapDimension(width=10, height=12),
    Map.UNKNOWN: MapDimension(),
}