from typing import NamedTuple, List

from deepred.polaris_env.pokemon_red.enums import Move

MOVES_INFO_DICT = {1: {'name': 'POUND', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 40, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 35, 'power': 40.0}, 2: {'name': 'KARATE_CHOP', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 50, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 25, 'power': 50.0}, 3: {'name': 'DOUBLESLAP', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 15, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 10, 'power': 37.8984375}, 4: {'name': 'COMET_PUNCH', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 18, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 15, 'power': 48.7265625}, 5: {'name': 'MEGA_PUNCH', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 77.0}, 6: {'name': 'PAY_DAY', 'effect': 'PAY_DAY_EFFECT', 'raw_power': 40, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 60.0}, 7: {'name': 'FIRE_PUNCH', 'effect': 'BURN_SIDE_EFFECT1', 'raw_power': 75, 'type': 'FIRE', 'type_id': 20, 'accuracy': 100, 'pp': 15, 'power': 79.6875}, 8: {'name': 'ICE_PUNCH', 'effect': 'FREEZE_SIDE_EFFECT', 'raw_power': 75, 'type': 'ICE', 'type_id': 25, 'accuracy': 100, 'pp': 15, 'power': 89.0625}, 9: {'name': 'THUNDERPUNCH', 'effect': 'PARALYZE_SIDE_EFFECT1', 'raw_power': 75, 'type': 'ELECTRIC', 'type_id': 23, 'accuracy': 100, 'pp': 15, 'power': 89.0625}, 10: {'name': 'SCRATCH', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 40, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 35, 'power': 40.0}, 11: {'name': 'VICEGRIP', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 55, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 55.0}, 12: {'name': 'GUILLOTINE', 'effect': 'OHKO_EFFECT', 'raw_power': 1, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 30, 'pp': 5, 'power': 40.8890625}, 13: {'name': 'RAZOR_WIND', 'effect': 'CHARGE_EFFECT', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 10, 'power': 52.5}, 14: {'name': 'SWORDS_DANCE', 'effect': 'ATTACK_UP2_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 20.0}, 15: {'name': 'CUT', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 50, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 95, 'pp': 30, 'power': 49.375}, 16: {'name': 'GUST', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 40, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 35, 'power': 40.0}, 17: {'name': 'WING_ATTACK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 35, 'type': 'FLYING', 'type_id': 2, 'accuracy': 100, 'pp': 35, 'power': 35.0}, 18: {'name': 'WHIRLWIND', 'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 0.0}, 19: {'name': 'FLY', 'effect': 'FLY_EFFECT', 'raw_power': 70, 'type': 'FLYING', 'type_id': 2, 'accuracy': 95, 'pp': 15, 'power': 64.8046875}, 20: {'name': 'BIND', 'effect': 'TRAPPING_EFFECT', 'raw_power': 15, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 20, 'power': 56.25}, 21: {'name': 'SLAM', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 20, 'power': 75.0}, 22: {'name': 'VINE_WHIP', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 35, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 10, 'power': 30.625}, 23: {'name': 'STOMP', 'effect': 'FLINCH_SIDE_EFFECT2', 'raw_power': 65, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 105.0}, 24: {'name': 'DOUBLE_KICK', 'effect': 'ATTACK_TWICE_EFFECT', 'raw_power': 30, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 100, 'pp': 30, 'power': 60.0}, 25: {'name': 'MEGA_KICK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 120, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 5, 'power': 91.40625}, 26: {'name': 'JUMP_KICK', 'effect': 'JUMP_KICK_EFFECT', 'raw_power': 70, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 95, 'pp': 25, 'power': 62.212500000000006}, 27: {'name': 'ROLLING_KICK', 'effect': 'FLINCH_SIDE_EFFECT2', 'raw_power': 60, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 85, 'pp': 15, 'power': 90.234375}, 28: {'name': 'SAND_ATTACK', 'effect': 'ACCURACY_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 9.375}, 29: {'name': 'HEADBUTT', 'effect': 'FLINCH_SIDE_EFFECT2', 'raw_power': 70, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 103.125}, 30: {'name': 'HORN_ATTACK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 65, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 25, 'power': 65.0}, 31: {'name': 'FURY_ATTACK', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 15, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 43.3125}, 32: {'name': 'HORN_DRILL', 'effect': 'OHKO_EFFECT', 'raw_power': 1, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 30, 'pp': 5, 'power': 40.8890625}, 33: {'name': 'TACKLE', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 35, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 95, 'pp': 35, 'power': 34.5625}, 34: {'name': 'BODY_SLAM', 'effect': 'PARALYZE_SIDE_EFFECT2', 'raw_power': 85, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 98.4375}, 35: {'name': 'WRAP', 'effect': 'TRAPPING_EFFECT', 'raw_power': 15, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 57.75}, 36: {'name': 'TAKE_DOWN', 'effect': 'RECOIL_EFFECT', 'raw_power': 90, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 77.9625}, 37: {'name': 'THRASH', 'effect': 'THRASH_PETAL_DANCE_EFFECT', 'raw_power': 90, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 81.0}, 38: {'name': 'DOUBLE_EDGE', 'effect': 'RECOIL_EFFECT', 'raw_power': 100, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 84.375}, 39: {'name': 'TAIL_WHIP', 'effect': 'DEFENSE_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 40: {'name': 'POISON_STING', 'effect': 'POISON_SIDE_EFFECT1', 'raw_power': 15, 'type': 'POISON', 'type_id': 3, 'accuracy': 100, 'pp': 35, 'power': 25.0}, 41: {'name': 'TWINEEDLE', 'effect': 'TWINEEDLE_EFFECT', 'raw_power': 25, 'type': 'BUG', 'type_id': 7, 'accuracy': 100, 'pp': 20, 'power': 62.0}, 42: {'name': 'PIN_MISSILE', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 14, 'type': 'BUG', 'type_id': 7, 'accuracy': 85, 'pp': 20, 'power': 40.425000000000004}, 43: {'name': 'LEER', 'effect': 'DEFENSE_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 44: {'name': 'BITE', 'effect': 'FLINCH_SIDE_EFFECT1', 'raw_power': 60, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 25, 'power': 80.0}, 45: {'name': 'GROWL', 'effect': 'ATTACK_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 40, 'power': 10.0}, 46: {'name': 'ROAR', 'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 0.0}, 47: {'name': 'SING', 'effect': 'SLEEP_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 55, 'pp': 15, 'power': 16.640625}, 48: {'name': 'SUPERSONIC', 'effect': 'CONFUSION_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 55, 'pp': 20, 'power': 8.875}, 49: {'name': 'SONICBOOM', 'effect': 'SPECIAL_DAMAGE_EFFECT', 'raw_power': 1, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 90, 'pp': 20, 'power': 39.975}, 50: {'name': 'DISABLE', 'effect': 'DISABLE_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 55, 'pp': 20, 'power': 17.75}, 51: {'name': 'ACID', 'effect': 'DEFENSE_DOWN_SIDE_EFFECT', 'raw_power': 40, 'type': 'POISON', 'type_id': 3, 'accuracy': 100, 'pp': 30, 'power': 50.0}, 52: {'name': 'EMBER', 'effect': 'BURN_SIDE_EFFECT1', 'raw_power': 40, 'type': 'FIRE', 'type_id': 20, 'accuracy': 100, 'pp': 25, 'power': 50.0}, 53: {'name': 'FLAMETHROWER', 'effect': 'BURN_SIDE_EFFECT1', 'raw_power': 95, 'type': 'FIRE', 'type_id': 20, 'accuracy': 100, 'pp': 15, 'power': 98.4375}, 54: {'name': 'MIST', 'effect': 'MIST_EFFECT', 'raw_power': 0, 'type': 'ICE', 'type_id': 25, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 55: {'name': 'WATER_GUN', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 40, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 25, 'power': 40.0}, 56: {'name': 'HYDRO_PUMP', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 120, 'type': 'WATER', 'type_id': 21, 'accuracy': 80, 'pp': 5, 'power': 92.625}, 57: {'name': 'SURF', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 95, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 15, 'power': 89.0625}, 58: {'name': 'ICE_BEAM', 'effect': 'FREEZE_SIDE_EFFECT', 'raw_power': 95, 'type': 'ICE', 'type_id': 25, 'accuracy': 100, 'pp': 10, 'power': 100.625}, 59: {'name': 'BLIZZARD', 'effect': 'FREEZE_SIDE_EFFECT', 'raw_power': 120, 'type': 'ICE', 'type_id': 25, 'accuracy': 90, 'pp': 5, 'power': 110.90624999999999}, 60: {'name': 'PSYBEAM', 'effect': 'CONFUSION_SIDE_EFFECT', 'raw_power': 65, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 20, 'power': 95.0}, 61: {'name': 'BUBBLEBEAM', 'effect': 'SPEED_DOWN_SIDE_EFFECT', 'raw_power': 65, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 20, 'power': 75.0}, 62: {'name': 'AURORA_BEAM', 'effect': 'ATTACK_DOWN_SIDE_EFFECT', 'raw_power': 65, 'type': 'ICE', 'type_id': 25, 'accuracy': 100, 'pp': 20, 'power': 75.0}, 63: {'name': 'HYPER_BEAM', 'effect': 'HYPER_BEAM_EFFECT', 'raw_power': 150, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 90, 'pp': 5, 'power': 88.725}, 64: {'name': 'PECK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 35, 'type': 'FLYING', 'type_id': 2, 'accuracy': 100, 'pp': 35, 'power': 35.0}, 65: {'name': 'DRILL_PECK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'FLYING', 'type_id': 2, 'accuracy': 100, 'pp': 20, 'power': 80.0}, 66: {'name': 'SUBMISSION', 'effect': 'RECOIL_EFFECT', 'raw_power': 80, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 80, 'pp': 25, 'power': 68.39999999999999}, 67: {'name': 'LOW_KICK', 'effect': 'FLINCH_SIDE_EFFECT2', 'raw_power': 50, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 90, 'pp': 20, 'power': 87.75}, 68: {'name': 'COUNTER', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 1, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 100, 'pp': 20, 'power': 1.0}, 69: {'name': 'SEISMIC_TOSS', 'effect': 'SPECIAL_DAMAGE_EFFECT', 'raw_power': 1, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 100, 'pp': 20, 'power': 41.0}, 70: {'name': 'STRENGTH', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 75.0}, 71: {'name': 'ABSORB', 'effect': 'DRAIN_HP_EFFECT', 'raw_power': 20, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 20, 'power': 30.0}, 72: {'name': 'MEGA_DRAIN', 'effect': 'DRAIN_HP_EFFECT', 'raw_power': 40, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 10, 'power': 52.5}, 73: {'name': 'LEECH_SEED', 'effect': 'LEECH_SEED_EFFECT', 'raw_power': 0, 'type': 'GRASS', 'type_id': 22, 'accuracy': 90, 'pp': 10, 'power': 34.125}, 74: {'name': 'GROWTH', 'effect': 'SPECIAL_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 40, 'power': 10.0}, 75: {'name': 'RAZOR_LEAF', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 55, 'type': 'GRASS', 'type_id': 22, 'accuracy': 95, 'pp': 25, 'power': 54.3125}, 76: {'name': 'SOLARBEAM', 'effect': 'CHARGE_EFFECT', 'raw_power': 120, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 10, 'power': 84.0}, 77: {'name': 'POISONPOWDER', 'effect': 'POISON_EFFECT', 'raw_power': 0, 'type': 'POISON', 'type_id': 3, 'accuracy': 75, 'pp': 35, 'power': 18.75}, 78: {'name': 'STUN_SPORE', 'effect': 'PARALYZE_EFFECT', 'raw_power': 0, 'type': 'GRASS', 'type_id': 22, 'accuracy': 75, 'pp': 30, 'power': 28.125}, 79: {'name': 'SLEEP_POWDER', 'effect': 'SLEEP_EFFECT', 'raw_power': 0, 'type': 'GRASS', 'type_id': 22, 'accuracy': 75, 'pp': 15, 'power': 17.578125}, 80: {'name': 'PETAL_DANCE', 'effect': 'THRASH_PETAL_DANCE_EFFECT', 'raw_power': 70, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 20, 'power': 63.0}, 81: {'name': 'STRING_SHOT', 'effect': 'SPEED_DOWN1_EFFECT', 'raw_power': 0, 'type': 'BUG', 'type_id': 7, 'accuracy': 95, 'pp': 40, 'power': 9.875}, 82: {'name': 'DRAGON_RAGE', 'effect': 'SPECIAL_DAMAGE_EFFECT', 'raw_power': 1, 'type': 'DRAGON', 'type_id': 26, 'accuracy': 100, 'pp': 10, 'power': 35.875}, 83: {'name': 'FIRE_SPIN', 'effect': 'TRAPPING_EFFECT', 'raw_power': 15, 'type': 'FIRE', 'type_id': 20, 'accuracy': 70, 'pp': 15, 'power': 52.03125}, 84: {'name': 'THUNDERSHOCK', 'effect': 'PARALYZE_SIDE_EFFECT1', 'raw_power': 40, 'type': 'ELECTRIC', 'type_id': 23, 'accuracy': 100, 'pp': 30, 'power': 60.0}, 85: {'name': 'THUNDERBOLT', 'effect': 'PARALYZE_SIDE_EFFECT1', 'raw_power': 95, 'type': 'ELECTRIC', 'type_id': 23, 'accuracy': 100, 'pp': 15, 'power': 107.8125}, 86: {'name': 'THUNDER_WAVE', 'effect': 'PARALYZE_EFFECT', 'raw_power': 0, 'type': 'ELECTRIC', 'type_id': 23, 'accuracy': 100, 'pp': 20, 'power': 30.0}, 87: {'name': 'THUNDER', 'effect': 'PARALYZE_SIDE_EFFECT1', 'raw_power': 120, 'type': 'ELECTRIC', 'type_id': 23, 'accuracy': 70, 'pp': 10, 'power': 113.31250000000001}, 88: {'name': 'ROCK_THROW', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 50, 'type': 'ROCK', 'type_id': 5, 'accuracy': 65, 'pp': 15, 'power': 42.7734375}, 89: {'name': 'EARTHQUAKE', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 100, 'type': 'GROUND', 'type_id': 4, 'accuracy': 100, 'pp': 10, 'power': 87.5}, 90: {'name': 'FISSURE', 'effect': 'OHKO_EFFECT', 'raw_power': 1, 'type': 'GROUND', 'type_id': 4, 'accuracy': 30, 'pp': 5, 'power': 40.8890625}, 91: {'name': 'DIG', 'effect': 'CHARGE_EFFECT', 'raw_power': 100, 'type': 'GROUND', 'type_id': 4, 'accuracy': 100, 'pp': 10, 'power': 70.0}, 92: {'name': 'TOXIC', 'effect': 'POISON_EFFECT', 'raw_power': 0, 'type': 'POISON', 'type_id': 3, 'accuracy': 85, 'pp': 10, 'power': 16.84375}, 93: {'name': 'CONFUSION', 'effect': 'CONFUSION_SIDE_EFFECT', 'raw_power': 50, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 25, 'power': 80.0}, 94: {'name': 'PSYCHIC_M', 'effect': 'SPECIAL_DOWN_SIDE_EFFECT', 'raw_power': 90, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 10, 'power': 87.5}, 95: {'name': 'HYPNOSIS', 'effect': 'SLEEP_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 60, 'pp': 20, 'power': 18.0}, 96: {'name': 'MEDITATE', 'effect': 'ATTACK_UP1_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 40, 'power': 10.0}, 97: {'name': 'AGILITY', 'effect': 'SPEED_UP2_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 30, 'power': 30.0}, 98: {'name': 'QUICK_ATTACK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 40, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 40.0}, 99: {'name': 'RAGE', 'effect': 'RAGE_EFFECT', 'raw_power': 20, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 40.0}, 100: {'name': 'TELEPORT', 'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 20, 'power': 0.0}, 101: {'name': 'NIGHT_SHADE', 'effect': 'SPECIAL_DAMAGE_EFFECT', 'raw_power': 0, 'type': 'GHOST', 'type_id': 8, 'accuracy': 100, 'pp': 15, 'power': 37.5}, 102: {'name': 'MIMIC', 'effect': 'MIMIC_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 8.75}, 103: {'name': 'SCREECH', 'effect': 'DEFENSE_DOWN2_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 40, 'power': 19.25}, 104: {'name': 'DOUBLE_TEAM', 'effect': 'EVASION_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 18.75}, 105: {'name': 'RECOVER', 'effect': 'HEAL_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 20.0}, 106: {'name': 'HARDEN', 'effect': 'DEFENSE_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 107: {'name': 'MINIMIZE', 'effect': 'EVASION_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 20.0}, 108: {'name': 'SMOKESCREEN', 'effect': 'ACCURACY_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 10.0}, 109: {'name': 'CONFUSE_RAY', 'effect': 'CONFUSION_EFFECT', 'raw_power': 0, 'type': 'GHOST', 'type_id': 8, 'accuracy': 100, 'pp': 10, 'power': 8.75}, 110: {'name': 'WITHDRAW', 'effect': 'DEFENSE_UP1_EFFECT', 'raw_power': 0, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 40, 'power': 10.0}, 111: {'name': 'DEFENSE_CURL', 'effect': 'DEFENSE_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 40, 'power': 10.0}, 112: {'name': 'BARRIER', 'effect': 'DEFENSE_UP2_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 30, 'power': 20.0}, 113: {'name': 'LIGHT_SCREEN', 'effect': 'LIGHT_SCREEN_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 30, 'power': 20.0}, 114: {'name': 'HAZE', 'effect': 'HAZE_EFFECT', 'raw_power': 0, 'type': 'ICE', 'type_id': 25, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 115: {'name': 'REFLECT', 'effect': 'REFLECT_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 20, 'power': 20.0}, 116: {'name': 'FOCUS_ENERGY', 'effect': 'FOCUS_ENERGY_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 20.0}, 117: {'name': 'BIDE', 'effect': 'BIDE_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 35.0}, 118: {'name': 'METRONOME', 'effect': 'METRONOME_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 52.5}, 119: {'name': 'MIRROR_MOVE', 'effect': 'MIRROR_MOVE_EFFECT', 'raw_power': 0, 'type': 'FLYING', 'type_id': 2, 'accuracy': 100, 'pp': 20, 'power': 30.0}, 120: {'name': 'SELFDESTRUCT', 'effect': 'EXPLODE_EFFECT', 'raw_power': 130, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 5, 'power': 34.125}, 121: {'name': 'EGG_BOMB', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 100, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 10, 'power': 82.03125}, 122: {'name': 'LICK', 'effect': 'PARALYZE_SIDE_EFFECT2', 'raw_power': 20, 'type': 'GHOST', 'type_id': 8, 'accuracy': 100, 'pp': 30, 'power': 40.0}, 123: {'name': 'SMOG', 'effect': 'POISON_SIDE_EFFECT2', 'raw_power': 20, 'type': 'POISON', 'type_id': 3, 'accuracy': 70, 'pp': 20, 'power': 46.25}, 124: {'name': 'SLUDGE', 'effect': 'POISON_SIDE_EFFECT2', 'raw_power': 65, 'type': 'POISON', 'type_id': 3, 'accuracy': 100, 'pp': 20, 'power': 95.0}, 125: {'name': 'BONE_CLUB', 'effect': 'FLINCH_SIDE_EFFECT1', 'raw_power': 65, 'type': 'GROUND', 'type_id': 4, 'accuracy': 85, 'pp': 20, 'power': 81.8125}, 126: {'name': 'FIRE_BLAST', 'effect': 'BURN_SIDE_EFFECT2', 'raw_power': 120, 'type': 'FIRE', 'type_id': 20, 'accuracy': 85, 'pp': 5, 'power': 101.66406250000001}, 127: {'name': 'WATERFALL', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 15, 'power': 75.0}, 128: {'name': 'CLAMP', 'effect': 'TRAPPING_EFFECT', 'raw_power': 35, 'type': 'WATER', 'type_id': 21, 'accuracy': 75, 'pp': 10, 'power': 114.84375}, 129: {'name': 'SWIFT', 'effect': 'SWIFT_EFFECT', 'raw_power': 60, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 80.0}, 130: {'name': 'SKULL_BASH', 'effect': 'CHARGE_EFFECT', 'raw_power': 100, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 75.0}, 131: {'name': 'SPIKE_CANNON', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 20, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 15, 'power': 56.25}, 132: {'name': 'CONSTRICT', 'effect': 'SPEED_DOWN_SIDE_EFFECT', 'raw_power': 10, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 35, 'power': 20.0}, 133: {'name': 'AMNESIA', 'effect': 'SPECIAL_UP2_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 20, 'power': 20.0}, 134: {'name': 'KINESIS', 'effect': 'ACCURACY_DOWN1_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 80, 'pp': 15, 'power': 8.90625}, 135: {'name': 'SOFTBOILED', 'effect': 'HEAL_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 17.5}, 136: {'name': 'HI_JUMP_KICK', 'effect': 'JUMP_KICK_EFFECT', 'raw_power': 85, 'type': 'FIGHTING', 'type_id': 1, 'accuracy': 90, 'pp': 20, 'power': 74.1}, 137: {'name': 'GLARE', 'effect': 'PARALYZE_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 30, 'power': 28.125}, 138: {'name': 'DREAM_EATER', 'effect': 'DREAM_EATER_EFFECT', 'raw_power': 100, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 15, 'power': 30.9375}, 139: {'name': 'POISON_GAS', 'effect': 'POISON_EFFECT', 'raw_power': 0, 'type': 'POISON', 'type_id': 3, 'accuracy': 55, 'pp': 40, 'power': 17.75}, 140: {'name': 'BARRAGE', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 15, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 85, 'pp': 20, 'power': 43.3125}, 141: {'name': 'LEECH_LIFE', 'effect': 'DRAIN_HP_EFFECT', 'raw_power': 20, 'type': 'BUG', 'type_id': 7, 'accuracy': 100, 'pp': 15, 'power': 28.125}, 142: {'name': 'LOVELY_KISS', 'effect': 'SLEEP_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 75, 'pp': 10, 'power': 16.40625}, 143: {'name': 'SKY_ATTACK', 'effect': 'CHARGE_EFFECT', 'raw_power': 140, 'type': 'FLYING', 'type_id': 2, 'accuracy': 90, 'pp': 5, 'power': 88.725}, 144: {'name': 'TRANSFORM', 'effect': 'TRANSFORM_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 8.75}, 145: {'name': 'BUBBLE', 'effect': 'SPEED_DOWN_SIDE_EFFECT', 'raw_power': 20, 'type': 'WATER', 'type_id': 21, 'accuracy': 100, 'pp': 30, 'power': 30.0}, 146: {'name': 'DIZZY_PUNCH', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 70, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 61.25}, 147: {'name': 'SPORE', 'effect': 'SLEEP_EFFECT', 'raw_power': 0, 'type': 'GRASS', 'type_id': 22, 'accuracy': 100, 'pp': 15, 'power': 18.75}, 148: {'name': 'FLASH', 'effect': 'ACCURACY_DOWN1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 70, 'pp': 20, 'power': 9.25}, 149: {'name': 'PSYWAVE', 'effect': 'SPECIAL_DAMAGE_EFFECT', 'raw_power': 1, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 80, 'pp': 15, 'power': 36.515625}, 150: {'name': 'SPLASH', 'effect': 'SPLASH_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 40, 'power': 0.0}, 151: {'name': 'ACID_ARMOR', 'effect': 'DEFENSE_UP2_EFFECT', 'raw_power': 0, 'type': 'POISON', 'type_id': 3, 'accuracy': 100, 'pp': 40, 'power': 20.0}, 152: {'name': 'CRABHAMMER', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 90, 'type': 'WATER', 'type_id': 21, 'accuracy': 85, 'pp': 10, 'power': 75.796875}, 153: {'name': 'EXPLOSION', 'effect': 'EXPLODE_EFFECT', 'raw_power': 170, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 5, 'power': 45.5}, 154: {'name': 'FURY_SWIPES', 'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'raw_power': 18, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 80, 'pp': 15, 'power': 48.09375}, 155: {'name': 'BONEMERANG', 'effect': 'ATTACK_TWICE_EFFECT', 'raw_power': 50, 'type': 'GROUND', 'type_id': 4, 'accuracy': 90, 'pp': 10, 'power': 85.3125}, 156: {'name': 'REST', 'effect': 'HEAL_EFFECT', 'raw_power': 0, 'type': 'PSYCHIC_TYPE', 'type_id': 24, 'accuracy': 100, 'pp': 10, 'power': 17.5}, 157: {'name': 'ROCK_SLIDE', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 75, 'type': 'ROCK', 'type_id': 5, 'accuracy': 90, 'pp': 10, 'power': 63.984375}, 158: {'name': 'HYPER_FANG', 'effect': 'FLINCH_SIDE_EFFECT1', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 90, 'pp': 15, 'power': 91.40625}, 159: {'name': 'SHARPEN', 'effect': 'ATTACK_UP1_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 160: {'name': 'CONVERSION', 'effect': 'CONVERSION_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 30, 'power': 10.0}, 161: {'name': 'TRI_ATTACK', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 80, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 70.0}, 162: {'name': 'SUPER_FANG', 'effect': 'SUPER_FANG_EFFECT', 'raw_power': 1, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 90, 'pp': 10, 'power': 34.978125}, 163: {'name': 'SLASH', 'effect': 'NO_ADDITIONAL_EFFECT', 'raw_power': 70, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 20, 'power': 70.0}, 164: {'name': 'SUBSTITUTE', 'effect': 'SUBSTITUTE_EFFECT', 'raw_power': 0, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 35.0}, 165: {'name': 'STRUGGLE', 'effect': 'RECOIL_EFFECT', 'raw_power': 50, 'type': 'NORMAL', 'type_id': 0, 'accuracy': 100, 'pp': 10, 'power': 39.375}}


class MoveInfo(NamedTuple):
    effect: str
    type_id : int
    raw_power: int
    power: float
    accuracy: int
    pp: int

    def actual_power(
            self,
            pokemon_types: List[int]
    ):
        """
        Computes the actual power based on the pokemon types.
        """
        mult = 1.
        if self.raw_power > 0 and self.type_id in pokemon_types:
            mult += 0.5
        return self.power * mult


MovesInfo = {
    Move.NO_MOVE: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=0, power=0, accuracy=0, pp=0),
    Move.POUND: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=40, power=40.0, accuracy=100, pp=35),
    Move.KARATE_CHOP: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=50, power=50.0, accuracy=100, pp=25),
    Move.DOUBLESLAP: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=15, power=37.8984375,
                              accuracy=85, pp=10),
    Move.COMET_PUNCH: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=18, power=48.7265625,
                               accuracy=85, pp=15),
    Move.MEGA_PUNCH: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=80, power=77.0, accuracy=85, pp=20),
    Move.PAY_DAY: MoveInfo(effect="PAY_DAY_EFFECT", type_id=0, raw_power=40, power=60.0, accuracy=100, pp=20),
    Move.FIRE_PUNCH: MoveInfo(effect="BURN_SIDE_EFFECT1", type_id=20, raw_power=75, power=79.6875, accuracy=100, pp=15),
    Move.ICE_PUNCH: MoveInfo(effect="FREEZE_SIDE_EFFECT", type_id=25, raw_power=75, power=89.0625, accuracy=100, pp=15),
    Move.THUNDERPUNCH: MoveInfo(effect="PARALYZE_SIDE_EFFECT1", type_id=23, raw_power=75, power=89.0625, accuracy=100,
                                pp=15),
    Move.SCRATCH: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=40, power=40.0, accuracy=100, pp=35),
    Move.VICEGRIP: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=55, power=55.0, accuracy=100, pp=30),
    Move.GUILLOTINE: MoveInfo(effect="OHKO_EFFECT", type_id=0, raw_power=1, power=40.8890625, accuracy=30, pp=5),
    Move.RAZOR_WIND: MoveInfo(effect="CHARGE_EFFECT", type_id=0, raw_power=80, power=52.5, accuracy=75, pp=10),
    Move.SWORDS_DANCE: MoveInfo(effect="ATTACK_UP2_EFFECT", type_id=0, raw_power=0, power=20.0, accuracy=100, pp=30),
    Move.CUT: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=50, power=49.375, accuracy=95, pp=30),
    Move.GUST: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=40, power=40.0, accuracy=100, pp=35),
    Move.WING_ATTACK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=2, raw_power=35, power=35.0, accuracy=100, pp=35),
    Move.WHIRLWIND: MoveInfo(effect="SWITCH_AND_TELEPORT_EFFECT", type_id=0, raw_power=0, power=0.0, accuracy=85,
                             pp=20),
    Move.FLY: MoveInfo(effect="FLY_EFFECT", type_id=2, raw_power=70, power=64.8046875, accuracy=95, pp=15),
    Move.BIND: MoveInfo(effect="TRAPPING_EFFECT", type_id=0, raw_power=15, power=56.25, accuracy=75, pp=20),
    Move.SLAM: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=80, power=75.0, accuracy=75, pp=20),
    Move.VINE_WHIP: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=22, raw_power=35, power=30.625, accuracy=100,
                             pp=10),
    Move.STOMP: MoveInfo(effect="FLINCH_SIDE_EFFECT2", type_id=0, raw_power=65, power=105.0, accuracy=100, pp=20),
    Move.DOUBLE_KICK: MoveInfo(effect="ATTACK_TWICE_EFFECT", type_id=1, raw_power=30, power=60.0, accuracy=100, pp=30),
    Move.MEGA_KICK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=120, power=91.40625, accuracy=75,
                             pp=5),
    Move.JUMP_KICK: MoveInfo(effect="JUMP_KICK_EFFECT", type_id=1, raw_power=70, power=62.212500000000006, accuracy=95,
                             pp=25),
    Move.ROLLING_KICK: MoveInfo(effect="FLINCH_SIDE_EFFECT2", type_id=1, raw_power=60, power=90.234375, accuracy=85,
                                pp=15),
    Move.SAND_ATTACK: MoveInfo(effect="ACCURACY_DOWN1_EFFECT", type_id=0, raw_power=0, power=9.375, accuracy=100,
                               pp=15),
    Move.HEADBUTT: MoveInfo(effect="FLINCH_SIDE_EFFECT2", type_id=0, raw_power=70, power=103.125, accuracy=100, pp=15),
    Move.HORN_ATTACK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=65, power=65.0, accuracy=100, pp=25),
    Move.FURY_ATTACK: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=15, power=43.3125, accuracy=85,
                               pp=20),
    Move.HORN_DRILL: MoveInfo(effect="OHKO_EFFECT", type_id=0, raw_power=1, power=40.8890625, accuracy=30, pp=5),
    Move.TACKLE: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=35, power=34.5625, accuracy=95, pp=35),
    Move.BODY_SLAM: MoveInfo(effect="PARALYZE_SIDE_EFFECT2", type_id=0, raw_power=85, power=98.4375, accuracy=100,
                             pp=15),
    Move.WRAP: MoveInfo(effect="TRAPPING_EFFECT", type_id=0, raw_power=15, power=57.75, accuracy=85, pp=20),
    Move.TAKE_DOWN: MoveInfo(effect="RECOIL_EFFECT", type_id=0, raw_power=90, power=77.9625, accuracy=85, pp=20),
    Move.THRASH: MoveInfo(effect="THRASH_PETAL_DANCE_EFFECT", type_id=0, raw_power=90, power=81.0, accuracy=100, pp=20),
    Move.DOUBLE_EDGE: MoveInfo(effect="RECOIL_EFFECT", type_id=0, raw_power=100, power=84.375, accuracy=100, pp=15),
    Move.TAIL_WHIP: MoveInfo(effect="DEFENSE_DOWN1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.POISON_STING: MoveInfo(effect="POISON_SIDE_EFFECT1", type_id=3, raw_power=15, power=25.0, accuracy=100, pp=35),
    Move.TWINEEDLE: MoveInfo(effect="TWINEEDLE_EFFECT", type_id=7, raw_power=25, power=62.0, accuracy=100, pp=20),
    Move.PIN_MISSILE: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=7, raw_power=14, power=40.425000000000004,
                               accuracy=85, pp=20),
    Move.LEER: MoveInfo(effect="DEFENSE_DOWN1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.BITE: MoveInfo(effect="FLINCH_SIDE_EFFECT1", type_id=0, raw_power=60, power=80.0, accuracy=100, pp=25),
    Move.GROWL: MoveInfo(effect="ATTACK_DOWN1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=40),
    Move.ROAR: MoveInfo(effect="SWITCH_AND_TELEPORT_EFFECT", type_id=0, raw_power=0, power=0.0, accuracy=100, pp=20),
    Move.SING: MoveInfo(effect="SLEEP_EFFECT", type_id=0, raw_power=0, power=16.640625, accuracy=55, pp=15),
    Move.SUPERSONIC: MoveInfo(effect="CONFUSION_EFFECT", type_id=0, raw_power=0, power=8.875, accuracy=55, pp=20),
    Move.SONICBOOM: MoveInfo(effect="SPECIAL_DAMAGE_EFFECT", type_id=0, raw_power=1, power=39.975, accuracy=90, pp=20),
    Move.DISABLE: MoveInfo(effect="DISABLE_EFFECT", type_id=0, raw_power=0, power=17.75, accuracy=55, pp=20),
    Move.ACID: MoveInfo(effect="DEFENSE_DOWN_SIDE_EFFECT", type_id=3, raw_power=40, power=50.0, accuracy=100, pp=30),
    Move.EMBER: MoveInfo(effect="BURN_SIDE_EFFECT1", type_id=20, raw_power=40, power=50.0, accuracy=100, pp=25),
    Move.FLAMETHROWER: MoveInfo(effect="BURN_SIDE_EFFECT1", type_id=20, raw_power=95, power=98.4375, accuracy=100,
                                pp=15),
    Move.MIST: MoveInfo(effect="MIST_EFFECT", type_id=25, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.WATER_GUN: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=21, raw_power=40, power=40.0, accuracy=100, pp=25),
    Move.HYDRO_PUMP: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=21, raw_power=120, power=92.625, accuracy=80,
                              pp=5),
    Move.SURF: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=21, raw_power=95, power=89.0625, accuracy=100, pp=15),
    Move.ICE_BEAM: MoveInfo(effect="FREEZE_SIDE_EFFECT", type_id=25, raw_power=95, power=100.625, accuracy=100, pp=10),
    Move.BLIZZARD: MoveInfo(effect="FREEZE_SIDE_EFFECT", type_id=25, raw_power=120, power=110.90624999999999,
                            accuracy=90, pp=5),
    Move.PSYBEAM: MoveInfo(effect="CONFUSION_SIDE_EFFECT", type_id=24, raw_power=65, power=95.0, accuracy=100, pp=20),
    Move.BUBBLEBEAM: MoveInfo(effect="SPEED_DOWN_SIDE_EFFECT", type_id=21, raw_power=65, power=75.0, accuracy=100,
                              pp=20),
    Move.AURORA_BEAM: MoveInfo(effect="ATTACK_DOWN_SIDE_EFFECT", type_id=25, raw_power=65, power=75.0, accuracy=100,
                               pp=20),
    Move.HYPER_BEAM: MoveInfo(effect="HYPER_BEAM_EFFECT", type_id=0, raw_power=150, power=88.725, accuracy=90, pp=5),
    Move.PECK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=2, raw_power=35, power=35.0, accuracy=100, pp=35),
    Move.DRILL_PECK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=2, raw_power=80, power=80.0, accuracy=100, pp=20),
    Move.SUBMISSION: MoveInfo(effect="RECOIL_EFFECT", type_id=1, raw_power=80, power=68.39999999999999, accuracy=80,
                              pp=25),
    Move.LOW_KICK: MoveInfo(effect="FLINCH_SIDE_EFFECT2", type_id=1, raw_power=50, power=87.75, accuracy=90, pp=20),
    Move.COUNTER: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=1, raw_power=1, power=1.0, accuracy=100, pp=20),
    Move.SEISMIC_TOSS: MoveInfo(effect="SPECIAL_DAMAGE_EFFECT", type_id=1, raw_power=1, power=41.0, accuracy=100,
                                pp=20),
    Move.STRENGTH: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=80, power=75.0, accuracy=100, pp=15),
    Move.ABSORB: MoveInfo(effect="DRAIN_HP_EFFECT", type_id=22, raw_power=20, power=30.0, accuracy=100, pp=20),
    Move.MEGA_DRAIN: MoveInfo(effect="DRAIN_HP_EFFECT", type_id=22, raw_power=40, power=52.5, accuracy=100, pp=10),
    Move.LEECH_SEED: MoveInfo(effect="LEECH_SEED_EFFECT", type_id=22, raw_power=0, power=34.125, accuracy=90, pp=10),
    Move.GROWTH: MoveInfo(effect="SPECIAL_UP1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=40),
    Move.RAZOR_LEAF: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=22, raw_power=55, power=54.3125, accuracy=95,
                              pp=25),
    Move.SOLARBEAM: MoveInfo(effect="CHARGE_EFFECT", type_id=22, raw_power=120, power=84.0, accuracy=100, pp=10),
    Move.POISONPOWDER: MoveInfo(effect="POISON_EFFECT", type_id=3, raw_power=0, power=18.75, accuracy=75, pp=35),
    Move.STUN_SPORE: MoveInfo(effect="PARALYZE_EFFECT", type_id=22, raw_power=0, power=28.125, accuracy=75, pp=30),
    Move.SLEEP_POWDER: MoveInfo(effect="SLEEP_EFFECT", type_id=22, raw_power=0, power=17.578125, accuracy=75, pp=15),
    Move.PETAL_DANCE: MoveInfo(effect="THRASH_PETAL_DANCE_EFFECT", type_id=22, raw_power=70, power=63.0, accuracy=100,
                               pp=20),
    Move.STRING_SHOT: MoveInfo(effect="SPEED_DOWN1_EFFECT", type_id=7, raw_power=0, power=9.875, accuracy=95, pp=40),
    Move.DRAGON_RAGE: MoveInfo(effect="SPECIAL_DAMAGE_EFFECT", type_id=26, raw_power=1, power=35.875, accuracy=100,
                               pp=10),
    Move.FIRE_SPIN: MoveInfo(effect="TRAPPING_EFFECT", type_id=20, raw_power=15, power=52.03125, accuracy=70, pp=15),
    Move.THUNDERSHOCK: MoveInfo(effect="PARALYZE_SIDE_EFFECT1", type_id=23, raw_power=40, power=60.0, accuracy=100,
                                pp=30),
    Move.THUNDERBOLT: MoveInfo(effect="PARALYZE_SIDE_EFFECT1", type_id=23, raw_power=95, power=107.8125, accuracy=100,
                               pp=15),
    Move.THUNDER_WAVE: MoveInfo(effect="PARALYZE_EFFECT", type_id=23, raw_power=0, power=30.0, accuracy=100, pp=20),
    Move.THUNDER: MoveInfo(effect="PARALYZE_SIDE_EFFECT1", type_id=23, raw_power=120, power=113.31250000000001,
                           accuracy=70, pp=10),
    Move.ROCK_THROW: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=5, raw_power=50, power=42.7734375, accuracy=65,
                              pp=15),
    Move.EARTHQUAKE: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=4, raw_power=100, power=87.5, accuracy=100, pp=10),
    Move.FISSURE: MoveInfo(effect="OHKO_EFFECT", type_id=4, raw_power=1, power=40.8890625, accuracy=30, pp=5),
    Move.DIG: MoveInfo(effect="CHARGE_EFFECT", type_id=4, raw_power=100, power=70.0, accuracy=100, pp=10),
    Move.TOXIC: MoveInfo(effect="POISON_EFFECT", type_id=3, raw_power=0, power=16.84375, accuracy=85, pp=10),
    Move.CONFUSION: MoveInfo(effect="CONFUSION_SIDE_EFFECT", type_id=24, raw_power=50, power=80.0, accuracy=100, pp=25),
    Move.PSYCHIC_M: MoveInfo(effect="SPECIAL_DOWN_SIDE_EFFECT", type_id=24, raw_power=90, power=87.5, accuracy=100,
                             pp=10),
    Move.HYPNOSIS: MoveInfo(effect="SLEEP_EFFECT", type_id=24, raw_power=0, power=18.0, accuracy=60, pp=20),
    Move.MEDITATE: MoveInfo(effect="ATTACK_UP1_EFFECT", type_id=24, raw_power=0, power=10.0, accuracy=100, pp=40),
    Move.AGILITY: MoveInfo(effect="SPEED_UP2_EFFECT", type_id=24, raw_power=0, power=30.0, accuracy=100, pp=30),
    Move.QUICK_ATTACK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=40, power=40.0, accuracy=100,
                                pp=30),
    Move.RAGE: MoveInfo(effect="RAGE_EFFECT", type_id=0, raw_power=20, power=40.0, accuracy=100, pp=20),
    Move.TELEPORT: MoveInfo(effect="SWITCH_AND_TELEPORT_EFFECT", type_id=24, raw_power=0, power=0.0, accuracy=100,
                            pp=20),
    Move.NIGHT_SHADE: MoveInfo(effect="SPECIAL_DAMAGE_EFFECT", type_id=8, raw_power=0, power=37.5, accuracy=100, pp=15),
    Move.MIMIC: MoveInfo(effect="MIMIC_EFFECT", type_id=0, raw_power=0, power=8.75, accuracy=100, pp=10),
    Move.SCREECH: MoveInfo(effect="DEFENSE_DOWN2_EFFECT", type_id=0, raw_power=0, power=19.25, accuracy=85, pp=40),
    Move.DOUBLE_TEAM: MoveInfo(effect="EVASION_UP1_EFFECT", type_id=0, raw_power=0, power=18.75, accuracy=100, pp=15),
    Move.RECOVER: MoveInfo(effect="HEAL_EFFECT", type_id=0, raw_power=0, power=20.0, accuracy=100, pp=20),
    Move.HARDEN: MoveInfo(effect="DEFENSE_UP1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.MINIMIZE: MoveInfo(effect="EVASION_UP1_EFFECT", type_id=0, raw_power=0, power=20.0, accuracy=100, pp=20),
    Move.SMOKESCREEN: MoveInfo(effect="ACCURACY_DOWN1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=20),
    Move.CONFUSE_RAY: MoveInfo(effect="CONFUSION_EFFECT", type_id=8, raw_power=0, power=8.75, accuracy=100, pp=10),
    Move.WITHDRAW: MoveInfo(effect="DEFENSE_UP1_EFFECT", type_id=21, raw_power=0, power=10.0, accuracy=100, pp=40),
    Move.DEFENSE_CURL: MoveInfo(effect="DEFENSE_UP1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=40),
    Move.BARRIER: MoveInfo(effect="DEFENSE_UP2_EFFECT", type_id=24, raw_power=0, power=20.0, accuracy=100, pp=30),
    Move.LIGHT_SCREEN: MoveInfo(effect="LIGHT_SCREEN_EFFECT", type_id=24, raw_power=0, power=20.0, accuracy=100, pp=30),
    Move.HAZE: MoveInfo(effect="HAZE_EFFECT", type_id=25, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.REFLECT: MoveInfo(effect="REFLECT_EFFECT", type_id=24, raw_power=0, power=20.0, accuracy=100, pp=20),
    Move.FOCUS_ENERGY: MoveInfo(effect="FOCUS_ENERGY_EFFECT", type_id=0, raw_power=0, power=20.0, accuracy=100, pp=30),
    Move.BIDE: MoveInfo(effect="BIDE_EFFECT", type_id=0, raw_power=0, power=35.0, accuracy=100, pp=10),
    Move.METRONOME: MoveInfo(effect="METRONOME_EFFECT", type_id=0, raw_power=0, power=52.5, accuracy=100, pp=10),
    Move.MIRROR_MOVE: MoveInfo(effect="MIRROR_MOVE_EFFECT", type_id=2, raw_power=0, power=30.0, accuracy=100, pp=20),
    Move.SELFDESTRUCT: MoveInfo(effect="EXPLODE_EFFECT", type_id=0, raw_power=130, power=34.125, accuracy=100, pp=5),
    Move.EGG_BOMB: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=100, power=82.03125, accuracy=75,
                            pp=10),
    Move.LICK: MoveInfo(effect="PARALYZE_SIDE_EFFECT2", type_id=8, raw_power=20, power=40.0, accuracy=100, pp=30),
    Move.SMOG: MoveInfo(effect="POISON_SIDE_EFFECT2", type_id=3, raw_power=20, power=46.25, accuracy=70, pp=20),
    Move.SLUDGE: MoveInfo(effect="POISON_SIDE_EFFECT2", type_id=3, raw_power=65, power=95.0, accuracy=100, pp=20),
    Move.BONE_CLUB: MoveInfo(effect="FLINCH_SIDE_EFFECT1", type_id=4, raw_power=65, power=81.8125, accuracy=85, pp=20),
    Move.FIRE_BLAST: MoveInfo(effect="BURN_SIDE_EFFECT2", type_id=20, raw_power=120, power=101.66406250000001,
                              accuracy=85, pp=5),
    Move.WATERFALL: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=21, raw_power=80, power=75.0, accuracy=100, pp=15),
    Move.CLAMP: MoveInfo(effect="TRAPPING_EFFECT", type_id=21, raw_power=35, power=114.84375, accuracy=75, pp=10),
    Move.SWIFT: MoveInfo(effect="SWIFT_EFFECT", type_id=0, raw_power=60, power=80.0, accuracy=100, pp=20),
    Move.SKULL_BASH: MoveInfo(effect="CHARGE_EFFECT", type_id=0, raw_power=100, power=75.0, accuracy=100, pp=15),
    Move.SPIKE_CANNON: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=20, power=56.25, accuracy=100,
                                pp=15),
    Move.CONSTRICT: MoveInfo(effect="SPEED_DOWN_SIDE_EFFECT", type_id=0, raw_power=10, power=20.0, accuracy=100, pp=35),
    Move.AMNESIA: MoveInfo(effect="SPECIAL_UP2_EFFECT", type_id=24, raw_power=0, power=20.0, accuracy=100, pp=20),
    Move.KINESIS: MoveInfo(effect="ACCURACY_DOWN1_EFFECT", type_id=24, raw_power=0, power=8.90625, accuracy=80, pp=15),
    Move.SOFTBOILED: MoveInfo(effect="HEAL_EFFECT", type_id=0, raw_power=0, power=17.5, accuracy=100, pp=10),
    Move.HI_JUMP_KICK: MoveInfo(effect="JUMP_KICK_EFFECT", type_id=1, raw_power=85, power=74.1, accuracy=90, pp=20),
    Move.GLARE: MoveInfo(effect="PARALYZE_EFFECT", type_id=0, raw_power=0, power=28.125, accuracy=75, pp=30),
    Move.DREAM_EATER: MoveInfo(effect="DREAM_EATER_EFFECT", type_id=24, raw_power=100, power=30.9375, accuracy=100,
                               pp=15),
    Move.POISON_GAS: MoveInfo(effect="POISON_EFFECT", type_id=3, raw_power=0, power=17.75, accuracy=55, pp=40),
    Move.BARRAGE: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=15, power=43.3125, accuracy=85,
                           pp=20),
    Move.LEECH_LIFE: MoveInfo(effect="DRAIN_HP_EFFECT", type_id=7, raw_power=20, power=28.125, accuracy=100, pp=15),
    Move.LOVELY_KISS: MoveInfo(effect="SLEEP_EFFECT", type_id=0, raw_power=0, power=16.40625, accuracy=75, pp=10),
    Move.SKY_ATTACK: MoveInfo(effect="CHARGE_EFFECT", type_id=2, raw_power=140, power=88.725, accuracy=90, pp=5),
    Move.TRANSFORM: MoveInfo(effect="TRANSFORM_EFFECT", type_id=0, raw_power=0, power=8.75, accuracy=100, pp=10),
    Move.BUBBLE: MoveInfo(effect="SPEED_DOWN_SIDE_EFFECT", type_id=21, raw_power=20, power=30.0, accuracy=100, pp=30),
    Move.DIZZY_PUNCH: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=70, power=61.25, accuracy=100,
                               pp=10),
    Move.SPORE: MoveInfo(effect="SLEEP_EFFECT", type_id=22, raw_power=0, power=18.75, accuracy=100, pp=15),
    Move.FLASH: MoveInfo(effect="ACCURACY_DOWN1_EFFECT", type_id=0, raw_power=0, power=9.25, accuracy=70, pp=20),
    Move.PSYWAVE: MoveInfo(effect="SPECIAL_DAMAGE_EFFECT", type_id=24, raw_power=1, power=36.515625, accuracy=80,
                           pp=15),
    Move.SPLASH: MoveInfo(effect="SPLASH_EFFECT", type_id=0, raw_power=0, power=0.0, accuracy=100, pp=40),
    Move.ACID_ARMOR: MoveInfo(effect="DEFENSE_UP2_EFFECT", type_id=3, raw_power=0, power=20.0, accuracy=100, pp=40),
    Move.CRABHAMMER: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=21, raw_power=90, power=75.796875, accuracy=85,
                              pp=10),
    Move.EXPLOSION: MoveInfo(effect="EXPLODE_EFFECT", type_id=0, raw_power=170, power=45.5, accuracy=100, pp=5),
    Move.FURY_SWIPES: MoveInfo(effect="TWO_TO_FIVE_ATTACKS_EFFECT", type_id=0, raw_power=18, power=48.09375,
                               accuracy=80, pp=15),
    Move.BONEMERANG: MoveInfo(effect="ATTACK_TWICE_EFFECT", type_id=4, raw_power=50, power=85.3125, accuracy=90, pp=10),
    Move.REST: MoveInfo(effect="HEAL_EFFECT", type_id=24, raw_power=0, power=17.5, accuracy=100, pp=10),
    Move.ROCK_SLIDE: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=5, raw_power=75, power=63.984375, accuracy=90,
                              pp=10),
    Move.HYPER_FANG: MoveInfo(effect="FLINCH_SIDE_EFFECT1", type_id=0, raw_power=80, power=91.40625, accuracy=90,
                              pp=15),
    Move.SHARPEN: MoveInfo(effect="ATTACK_UP1_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.CONVERSION: MoveInfo(effect="CONVERSION_EFFECT", type_id=0, raw_power=0, power=10.0, accuracy=100, pp=30),
    Move.TRI_ATTACK: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=80, power=70.0, accuracy=100, pp=10),
    Move.SUPER_FANG: MoveInfo(effect="SUPER_FANG_EFFECT", type_id=0, raw_power=1, power=34.978125, accuracy=90, pp=10),
    Move.SLASH: MoveInfo(effect="NO_ADDITIONAL_EFFECT", type_id=0, raw_power=70, power=70.0, accuracy=100, pp=20),
    Move.SUBSTITUTE: MoveInfo(effect="SUBSTITUTE_EFFECT", type_id=0, raw_power=0, power=35.0, accuracy=100, pp=10),
    Move.STRUGGLE: MoveInfo(effect="RECOIL_EFFECT", type_id=0, raw_power=50, power=39.375, accuracy=100, pp=10),

}